Option Strict On
Option Explicit On

Imports System.Globalization
Imports System.Text.RegularExpressions
Imports AutoGenerateDiameter.Core
Imports Microsoft.VisualStudio.TestTools.UnitTesting

' Accuracy harness for cell-level OCR.
'
' Drop labelled, pre-cropped cell images into a "cell_samples" folder (see that folder's
' README for the naming convention). This test runs each image through the same Core OCR
' path the app uses (ManualCompareService.OcrCellImage) and reports the recognition accuracy.
'
' The test is Inconclusive when:
'   - Tesseract is not installed, or
'   - there are no sample images yet.
' Once at least MinimumSampleCount labelled samples exist, it asserts accuracy stays above
' AccuracyGate, so a regression in preprocessing or OCR settings fails the build.
<TestClass>
Public Class CellOcrAccuracyTests
    Private Const AccuracyGate As Double = 0.7
    Private Const MinimumSampleCount As Integer = 10

    ' Filename convention: <expected>[_r<row>]_<anything>.png   e.g. 65_r1_sample01.png, 60_r3_a.png
    Private Shared ReadOnly NamePattern As New Regex("^(?<value>\d{1,3})(?:_r(?<row>\d))?[_\-.]", RegexOptions.IgnoreCase)

    Public Property TestContext As TestContext

    <TestMethod>
    Public Sub CellOcrMeetsAccuracyGate()
        If TesseractRuntime.FindExecutable() Is Nothing Then
            Assert.Inconclusive("Tesseract OCR runtime not found; skipping cell OCR accuracy measurement.")
        End If

        Dim folder = ResolveSamplesFolder()
        If folder Is Nothing OrElse Not IO.Directory.Exists(folder) Then
            Assert.Inconclusive("No cell_samples folder found; add labelled cell images to measure accuracy.")
        End If

        Dim samples = IO.Directory.
            EnumerateFiles(folder, "*.*").
            Where(Function(file) {".png", ".jpg", ".jpeg", ".bmp", ".tif", ".tiff"}.Contains(IO.Path.GetExtension(file).ToLowerInvariant())).
            Select(AddressOf ParseSample).
            Where(Function(sample) sample IsNot Nothing).
            ToList()

        If samples.Count = 0 Then
            Assert.Inconclusive("cell_samples folder has no correctly named images; nothing to measure.")
        End If

        Dim service As New ManualCompareService()
        Dim correct = 0
        Dim failures As New List(Of String)

        For Each sample In samples
            Dim actual = ""
            Try
                actual = service.OcrCellImage(sample.Path, sample.Row)
            Catch ex As Exception
                actual = $"<error: {ex.Message}>"
            End Try
            If actual = sample.Expected Then
                correct += 1
            Else
                failures.Add($"  {IO.Path.GetFileName(sample.Path)}: expected '{sample.Expected}', got '{actual}'")
            End If
        Next

        Dim accuracy = correct / CDbl(samples.Count)
        TestContext?.WriteLine($"Cell OCR accuracy: {correct}/{samples.Count} = {accuracy:P1}")
        If failures.Count > 0 Then
            TestContext?.WriteLine("Misreads:")
            For Each line In failures
                TestContext?.WriteLine(line)
            Next
        End If

        If samples.Count < MinimumSampleCount Then
            Assert.Inconclusive($"Only {samples.Count} sample(s); add at least {MinimumSampleCount} before gating on accuracy. Measured {accuracy:P1}.")
        End If

        Assert.IsTrue(
            accuracy >= AccuracyGate,
            $"Cell OCR accuracy {accuracy:P1} fell below the {AccuracyGate:P0} gate.{Environment.NewLine}{String.Join(Environment.NewLine, failures)}")
    End Sub

    Private Shared Function ParseSample(path As String) As Sample
        Dim match = NamePattern.Match(IO.Path.GetFileName(path))
        If Not match.Success Then Return Nothing
        Dim value = Integer.Parse(match.Groups("value").Value, CultureInfo.InvariantCulture).ToString(CultureInfo.InvariantCulture)
        Dim row = 1
        If match.Groups("row").Success Then row = Integer.Parse(match.Groups("row").Value, CultureInfo.InvariantCulture)
        Return New Sample With {.Path = path, .Expected = value, .Row = row}
    End Function

    ' Look beside the test binaries first (copied via vbproj), then walk up the source tree.
    Private Shared Function ResolveSamplesFolder() As String
        Dim fromEnv = Environment.GetEnvironmentVariable("CELL_SAMPLES_DIR")
        If Not String.IsNullOrWhiteSpace(fromEnv) AndAlso IO.Directory.Exists(fromEnv) Then Return fromEnv

        Dim cursor = New IO.DirectoryInfo(AppContext.BaseDirectory)
        While cursor IsNot Nothing
            Dim candidate = IO.Path.Combine(cursor.FullName, "cell_samples")
            If IO.Directory.Exists(candidate) Then Return candidate
            cursor = cursor.Parent
        End While
        Return Nothing
    End Function

    Private NotInheritable Class Sample
        Public Property Path As String = ""
        Public Property Expected As String = ""
        Public Property Row As Integer
    End Class
End Class
