Option Strict On
Option Explicit On

Imports AutoGenerateDiameter.Core
Imports Microsoft.VisualStudio.TestTools.UnitTesting

<TestClass>
Public Class EditLogStoreTests
    <TestMethod>
    Public Sub AppendThenReadAllPreservesHistoryAndValues()
        Dim path = IO.Path.Combine(IO.Path.GetTempPath(), $"{Guid.NewGuid()}.csv")
        Try
            Dim store As New EditLogStore(path)
            Dim stamp = New DateTime(2026, 6, 18, 9, 30, 0)

            store.Append({New EditLogEntry With {
                .Timestamp = stamp,
                .OperatorName = "somchai",
                .Target = "T-6 Row 1 L",
                .Field = "Value",
                .OldValue = "75",
                .NewValue = "76"
            }})

            ' A second append must extend the existing history, not replace it, and
            ' values containing commas/quotes must survive the CSV round-trip.
            store.Append({New EditLogEntry With {
                .Timestamp = stamp.AddMinutes(5),
                .OperatorName = "nong",
                .Target = "Header",
                .Field = "ITEM",
                .OldValue = "Old, ""A""",
                .NewValue = "New B"
            }})

            Dim entries = store.ReadAll()

            Assert.AreEqual(2, entries.Count)
            Assert.AreEqual("somchai", entries(0).OperatorName)
            Assert.AreEqual("T-6 Row 1 L", entries(0).Target)
            Assert.AreEqual("75", entries(0).OldValue)
            Assert.AreEqual("76", entries(0).NewValue)
            Assert.AreEqual(stamp, entries(0).Timestamp)
            Assert.AreEqual("Old, ""A""", entries(1).OldValue)
            Assert.AreEqual("New B", entries(1).NewValue)
        Finally
            If IO.File.Exists(path) Then IO.File.Delete(path)
        End Try
    End Sub

    <TestMethod>
    Public Sub ReadAllReturnsEmptyWhenFileMissing()
        Dim path = IO.Path.Combine(IO.Path.GetTempPath(), $"{Guid.NewGuid()}.csv")
        Dim store As New EditLogStore(path)
        Assert.AreEqual(0, store.ReadAll().Count)
    End Sub
End Class
