Option Strict On
Option Explicit On

Imports AutoGenerateDiameter.Core
Imports Microsoft.VisualStudio.TestTools.UnitTesting

<TestClass>
Public Class EmptyReportFactoryTests
    <TestMethod>
    Public Sub StartupReportContainsNoData()
        Dim report = EmptyReportFactory.Create()
        Dim sheet = report.Sheets.Single()

        Assert.AreEqual(1, report.Sheets.Count)
        Assert.AreEqual("", sheet.Item)
        Assert.AreEqual("", sheet.PlateNo)
        Assert.AreEqual("", sheet.DateTimeStamp)
        Assert.AreEqual("", sheet.DomeType)
        Assert.AreEqual("", sheet.Capa)
        Assert.AreEqual("", sheet.CoatLotNo)
        Assert.AreEqual("", sheet.OperatorName)
        Assert.AreEqual(0, sheet.Measurements.Count)
    End Sub
End Class
