Option Strict On
Option Explicit On

Imports AutoGenerateDiameter.Core
Imports Microsoft.VisualStudio.TestTools.UnitTesting

<TestClass>
Public Class ManualCompareServiceTests
    <TestMethod>
    Public Sub ExpectedValuesAreGroupedAndCompared()
        Dim sheet As New SheetData With {
            .CoatLotNo = "80632389",
            .Measurements = New List(Of Measurement) From {
                New Measurement With {
                    .TrayPosition = 1,
                    .RowNumber = 1,
                    .LotNumber = "98411573",
                    .RDiameter = 65,
                    .LDiameter = 66,
                    .TrayNumber = "175869",
                    .RPresent = True,
                    .LPresent = True
                }
            }
        }
        Dim tokens As ISet(Of String) = New HashSet(Of String) From {"80632389", "98411573", "65", "175869"}

        Dim result = New ManualCompareService().CompareTokens(tokens, sheet)
        Dim status = result.Items.ToDictionary(Function(item) $"{item.Category}:{item.Value}", Function(item) item.Found)

        Assert.IsTrue(status("Coat Lot:80632389"))
        Assert.IsTrue(status("Tray Lot:98411573"))
        Assert.IsTrue(status("Tray Number:175869"))
        Assert.IsTrue(status("Diameter:65"))
        Assert.IsFalse(status("Diameter:66"))
    End Sub
End Class
