Option Strict On
Option Explicit On

Imports AutoGenerateDiameter.Core
Imports Microsoft.VisualStudio.TestTools.UnitTesting

<TestClass>
Public Class ManualImageImportServiceTests
    <TestMethod>
    Public Sub TsvCoordinatesMapToTrayRowAndSide()
        Dim tsv = String.Join(
            Environment.NewLine,
            "level	page_num	block_num	par_num	line_num	word_num	left	top	width	height	conf	text",
            "1	1	0	0	0	0	0	0	1100	1000	-1	",
            "5	1	1	1	1	1	20	370	20	15	90	70",
            "5	1	1	1	1	2	75	370	20	15	85	71",
            "5	1	1	1	1	3	130	700	20	15	80	65"
        )

        Dim result = New ManualImageImportService().ParseTsv(tsv)

        Assert.AreEqual(2, result.Rows.Count)
        Assert.AreEqual(1, result.Rows(0).TrayPosition)
        Assert.AreEqual(1, result.Rows(0).RowNumber)
        Assert.AreEqual("70", result.Rows(0).RDiameter)
        Assert.AreEqual("71", result.Rows(0).LDiameter)
        Assert.AreEqual(13, result.Rows(1).TrayPosition)
    End Sub

    <TestMethod>
    Public Sub ReviewedRowsBuildAReport()
        Dim rows = {
            New ManualImportRow With {.TrayPosition = 1, .RowNumber = 1, .DipLotNumber = "LOT-1", .RDiameter = "70", .LDiameter = "71"}
        }

        Dim report = New ManualImageImportService().BuildReport(rows, "Semi", "P1", "2026-06-15", "HUT", "1", "C1", 83, 95)

        Assert.AreEqual(1, report.Sheets(0).Measurements.Count)
        Assert.AreEqual(70, report.Sheets(0).Measurements(0).RDiameter)
        Assert.AreEqual("LOT-1", report.Sheets(0).Measurements(0).LotNumber)
    End Sub

    <TestMethod>
    Public Sub HeaderOcrAddsDipLotAndJoinedRowNumberIsRemoved()
        Dim numericTsv = String.Join(
            Environment.NewLine,
            "level	page_num	block_num	par_num	line_num	word_num	left	top	width	height	conf	text",
            "1	1	0	0	0	0	0	0	1100	1000	-1	",
            "5	1	1	1	1	1	20	410	25	15	90	274"
        )
        Dim headerTsv = String.Join(
            Environment.NewLine,
            "level	page_num	block_num	par_num	line_num	word_num	left	top	width	height	conf	text",
            "1	1	0	0	0	0	0	0	1100	1000	-1	",
            "5	1	1	1	1	1	5	315	100	15	90	T-1(98387471)"
        )

        Dim result = New ManualImageImportService().ParseTsv(numericTsv, headerTsv)

        Assert.AreEqual(1, result.Rows.Count)
        Assert.AreEqual(2, result.Rows(0).RowNumber)
        Assert.AreEqual("74", result.Rows(0).RDiameter)
        Assert.AreEqual("98387471", result.Rows(0).DipLotNumber)
    End Sub
End Class
