Option Strict On
Option Explicit On

Imports AutoGenerateDiameter.Core
Imports Microsoft.VisualStudio.TestTools.UnitTesting

<TestClass>
Public Class MySqlReportLoaderTests
    <TestMethod>
    Public Sub QueryUsesNamedParameters()
        Dim query = MySqlReportLoader.LoadQuery()

        Assert.IsTrue(query.Contains("@place_code"))
        Assert.IsTrue(query.Contains("@lot_number"))
        Assert.IsFalse(query.Contains("%s"))
    End Sub
End Class
