Option Strict On
Option Explicit On

Imports AutoGenerateDiameter.Core
Imports Microsoft.VisualStudio.TestTools.UnitTesting

<TestClass>
Public Class ReportBuilderTests
    <TestMethod>
    Public Sub ZeroTrayLotGroupsByDipLotAndResequencesRows()
        Dim records = PairRecords("DIP-1", "0", "0", 40, "100001").
            Concat(PairRecords("DIP-1", "0", "0", 80, "100002")).
            ToList()

        Dim report = New ReportBuilder().Build(records, "2026-06-12 10:00")
        Dim rows = report.Sheets(0).Measurements

        Assert.AreEqual(2, rows.Count)
        Assert.AreEqual(1, rows(0).RowNumber)
        Assert.AreEqual(2, rows(1).RowNumber)
        Assert.AreEqual("DIP-1", rows(0).LotNumber)
    End Sub

    <TestMethod>
    Public Sub HardCoatUsesOneColumnPerDipLot()
        Dim records = PairRecords("DIP-1", "200", "1", 1, "100001").
            Concat(PairRecords("DIP-2", "201", "1", 1, "100002")).
            ToList()

        Dim report = New ReportBuilder().Build(records, "2026-06-12 10:00")
        Dim rows = report.Sheets(0).Measurements

        Assert.AreEqual(2, rows.Count)
        Assert.AreEqual(1, rows(0).TrayPosition)
        Assert.AreEqual(2, rows(1).TrayPosition)
    End Sub

    <TestMethod>
    Public Sub MoreThanTwentyTwoColumnsCreatesMultiplePages()
        Dim records As New List(Of SourceRecord)
        For index = 1 To 23
            records.AddRange(PairRecords($"DIP-{index}", index.ToString(), "1", 1, index.ToString()))
        Next

        Dim report = New ReportBuilder().Build(records, "2026-06-12 10:00")

        Assert.AreEqual(2, report.Sheets.Count)
        Assert.AreEqual(22, report.Sheets(0).Measurements.Count)
        Assert.AreEqual(1, report.Sheets(1).Measurements.Count)
    End Sub

    <TestMethod>
    Public Sub MissingTrayCreatesBlankColumn()
        Dim records = PairRecords("DIP-1", "100", "1", 1, "").
            Concat(PairRecords("DIP-2", "101", "1", 1, "100002")).
            ToList()

        Dim report = New ReportBuilder().Build(records, "2026-06-12 10:00")
        Dim row = report.Sheets(0).Measurements.Single()

        Assert.AreEqual(2, row.TrayPosition)
    End Sub

    <DataTestMethod>
    <DataRow("R", "R", True, False, False, False)>
    <DataRow("L", "L", False, True, False, False)>
    <DataRow("R", "P", True, False, False, False)>
    <DataRow("L", "P", False, True, False, False)>
    <DataRow("P", "P", True, True, False, False)>
    <DataRow("R", "L", False, False, True, False)>
    <DataRow("L", "R", False, False, False, True)>
    Public Sub MapsRlTypeAndRlpLot(
        rlType As String,
        rlpLot As String,
        rightPresent As Boolean,
        leftPresent As Boolean,
        rightDash As Boolean,
        leftDash As Boolean
    )
        Dim record As New SourceRecord With {
            .CoatLotNumber = "COAT-1",
            .CoatLotSeq = 1,
            .DipLotNumber = "DIP-1",
            .DipLotSeq = 1,
            .RlType = rlType,
            .RlpLot = rlpLot,
            .TrayNumber = "100001",
            .TrayLotNumber = "10",
            .UsedFlag = "1",
            .Diameter = 65
        }

        Dim measurement = New ReportBuilder().Build({record}, "2026-06-15").Sheets(0).Measurements.Single()

        Assert.AreEqual(rightPresent, measurement.RPresent)
        Assert.AreEqual(leftPresent, measurement.LPresent)
        Assert.AreEqual(rightDash, measurement.RDash)
        Assert.AreEqual(leftDash, measurement.LDash)
    End Sub

    Private Shared Function PairRecords(
        dipLot As String,
        trayLot As String,
        usedFlag As String,
        sequence As Integer,
        trayNumber As String
    ) As IEnumerable(Of SourceRecord)
        Return {"R", "L"}.Select(
            Function(side) New SourceRecord With {
                .CoatLotNumber = "COAT-1",
                .CoatLotSeq = sequence,
                .DipLotNumber = dipLot,
                .DipLotSeq = sequence,
                .RlType = side,
                .RlpLot = side,
                .TrayNumber = trayNumber,
                .ItemTypeName = "Semi",
                .RxArrangementNumber = "PL-1",
                .OrderRouteTypeName = "HUT",
                .TrayLotNumber = trayLot,
                .UsedFlag = usedFlag,
                .Diameter = 65
            }
        )
    End Function
End Class
