Option Strict On
Option Explicit On

Imports AutoGenerateDiameter.Core
Imports ClosedXML.Excel
Imports Microsoft.VisualStudio.TestTools.UnitTesting

<TestClass>
Public Class XlsxReportImporterTests
    <TestMethod>
    Public Sub ImportsRequiredColumnsAndBuildsReport()
        Dim path = IO.Path.Combine(IO.Path.GetTempPath(), $"{Guid.NewGuid()}.xlsx")
        Try
            Using workbook As New XLWorkbook()
                Dim sheet = workbook.AddWorksheet("Data")
                Dim headers = {
                    "coat_lot_number", "coat_lot_seq", "dip_lot_number", "diplt_seq",
                    "rl_type", "rlp_lot", "tray_number", "item_type_name", "rxarrangement_number",
                    "order_route_type_name", "traylot_number", "used_flag", "diameter"
                }
                For index = 0 To headers.Length - 1
                    sheet.Cell(1, index + 1).Value = headers(index)
                Next
                Dim values As Object() = {"COAT-1", 1, "DIP-1", 1, "R", "R", "123", "Semi", "PL-1", "HUT", "10", "1", 65}
                For index = 0 To values.Length - 1
                    sheet.Cell(2, index + 1).Value = XLCellValue.FromObject(values(index))
                Next
                workbook.SaveAs(path)
            End Using

            Dim report = New XlsxReportImporter().Import(path)

            Assert.AreEqual(1, report.Sheets.Count)
            Assert.AreEqual("000123", report.Sheets(0).Measurements(0).TrayNumber)
            Assert.IsTrue(report.Sheets(0).Measurements(0).RPresent)
            Assert.IsFalse(report.Sheets(0).Measurements(0).LPresent)
        Finally
            If IO.File.Exists(path) Then IO.File.Delete(path)
        End Try
    End Sub

    <TestMethod>
    Public Sub ImportsBlankDipLotAndSequence()
        Dim path = IO.Path.Combine(IO.Path.GetTempPath(), $"{Guid.NewGuid()}.xlsx")
        Try
            Using workbook As New XLWorkbook()
                Dim sheet = workbook.AddWorksheet("Data")
                Dim headers = {
                    "coat_lot_number", "coat_lot_seq", "dip_lot_number", "diplt_seq",
                    "rl_type", "rlp_lot", "tray_number", "item_type_name", "rxarrangement_number",
                    "order_route_type_name", "traylot_number", "used_flag", "diameter"
                }
                For index = 0 To headers.Length - 1
                    sheet.Cell(1, index + 1).Value = headers(index)
                Next
                Dim values As Object() = {"COAT-1", 1, "", "", "R", "R", "123", "Semi", "PL-1", "HUT", "10", "1", 65}
                For index = 0 To values.Length - 1
                    sheet.Cell(2, index + 1).Value = XLCellValue.FromObject(values(index))
                Next
                workbook.SaveAs(path)
            End Using

            Dim report = New XlsxReportImporter().Import(path)

            Assert.AreEqual(1, report.Sheets.Count)
            Assert.AreEqual("10", report.Sheets(0).Measurements(0).LotNumber)
        Finally
            If IO.File.Exists(path) Then IO.File.Delete(path)
        End Try
    End Sub

    <TestMethod>
    Public Sub FindsHeaderRowBelowReportTitle()
        Dim path = IO.Path.Combine(IO.Path.GetTempPath(), $"{Guid.NewGuid()}.xlsx")
        Try
            Using workbook As New XLWorkbook()
                Dim sheet = workbook.AddWorksheet("Data")
                sheet.Cell(1, 1).Value = "Diameter Export"
                sheet.Cell(2, 1).Value = "Generated by external system"
                Dim headers = {
                    "coat_lot_number", "coat_lot_seq", "dip_lot_number", "diplt_seq",
                    "rl_type", "rlp_lot", "tray_number", "item_type_name", "rxarrangement_number",
                    "order_route_type_name", "traylot_number", "used_flag", "diameter"
                }
                For index = 0 To headers.Length - 1
                    sheet.Cell(4, index + 1).Value = headers(index)
                Next
                Dim values As Object() = {"COAT-1", 1, "DIP-1", 1, "R", "R", "123", "Semi", "PL-1", "HUT", "10", "1", 65}
                For index = 0 To values.Length - 1
                    sheet.Cell(5, index + 1).Value = XLCellValue.FromObject(values(index))
                Next
                workbook.SaveAs(path)
            End Using

            Dim report = New XlsxReportImporter().Import(path)

            Assert.AreEqual(1, report.Sheets.Count)
            Assert.AreEqual("000123", report.Sheets(0).Measurements(0).TrayNumber)
        Finally
            If IO.File.Exists(path) Then IO.File.Delete(path)
        End Try
    End Sub

    <TestMethod>
    Public Sub ImportsSpacedHeaderNames()
        Dim path = IO.Path.Combine(IO.Path.GetTempPath(), $"{Guid.NewGuid()}.xlsx")
        Try
            Using workbook As New XLWorkbook()
                Dim sheet = workbook.AddWorksheet("Data")
                Dim headers = {
                    "Coat Lot Number", "Coat Lot Seq", "Dip Lot Number", "Dip Lot Seq",
                    "RL Type", "RLP Lot", "Tray Number", "Item Type Name", "RX Arrangement Number",
                    "Order Route Type Name", "Tray Lot Number", "Used Flag", "Diameter"
                }
                For index = 0 To headers.Length - 1
                    sheet.Cell(1, index + 1).Value = headers(index)
                Next
                Dim values As Object() = {"COAT-1", 1, "DIP-1", 1, "R", "R", "123", "Semi", "PL-1", "HUT", "10", "1", 65}
                For index = 0 To values.Length - 1
                    sheet.Cell(2, index + 1).Value = XLCellValue.FromObject(values(index))
                Next
                workbook.SaveAs(path)
            End Using

            Dim report = New XlsxReportImporter().Import(path)

            Assert.AreEqual(1, report.Sheets.Count)
            Assert.AreEqual("000123", report.Sheets(0).Measurements(0).TrayNumber)
        Finally
            If IO.File.Exists(path) Then IO.File.Delete(path)
        End Try
    End Sub
End Class
