Option Strict On
Option Explicit On

Imports AutoGenerateDiameter.Core
Imports System.Globalization

Public NotInheritable Class DatabaseLoadDialog
    Inherits Form

    Private ReadOnly _entries As New Dictionary(Of String, TextBox)
    Public ReadOnly Property Settings As New MySqlConnectionSettings()
    Public Property ProductionPlaceCode As String = ""
    Public Property CoatLotNumber As String = ""

    Public Sub New()
        Text = "Load from Database"
        FormBorderStyle = FormBorderStyle.FixedDialog
        StartPosition = FormStartPosition.CenterParent
        MaximizeBox = False
        MinimizeBox = False
        ClientSize = New Size(430, 410)

        Dim layout As New TableLayoutPanel With {
            .Dock = DockStyle.Fill,
            .Padding = New Padding(18),
            .ColumnCount = 2,
            .RowCount = 10
        }
        layout.ColumnStyles.Add(New ColumnStyle(SizeType.Absolute, 180))
        layout.ColumnStyles.Add(New ColumnStyle(SizeType.Percent, 100))
        Controls.Add(layout)

        AddHeading(layout, "MySQL Connection", 0)
        AddField(layout, "MySQL Host", "host", 1)
        AddField(layout, "MySQL Port", "port", 2, "3306")
        AddField(layout, "Database", "database", 3)
        AddField(layout, "Username", "username", 4)
        AddField(layout, "Password", "password", 5, password:=True)
        AddHeading(layout, "Report Criteria", 6)
        AddField(layout, "PPC", "ppc", 7)
        AddField(layout, "CLN", "cln", 8)

        Dim buttons As New FlowLayoutPanel With {.Dock = DockStyle.Fill, .FlowDirection = FlowDirection.RightToLeft}
        Dim load = New Button With {.Text = "Load", .DialogResult = DialogResult.None}
        AddHandler load.Click, AddressOf Submit
        buttons.Controls.Add(load)
        buttons.Controls.Add(New Button With {.Text = "Cancel", .DialogResult = DialogResult.Cancel})
        layout.Controls.Add(buttons, 0, 9)
        layout.SetColumnSpan(buttons, 2)
        AcceptButton = load
        CancelButton = buttons.Controls.OfType(Of Button)().Last()
    End Sub

    Private Shared Sub AddHeading(layout As TableLayoutPanel, text As String, row As Integer)
        Dim label = New Label With {.Text = text, .AutoSize = True, .Font = New Font("Segoe UI", 11, FontStyle.Bold)}
        layout.Controls.Add(label, 0, row)
        layout.SetColumnSpan(label, 2)
    End Sub

    Private Sub AddField(layout As TableLayoutPanel, label As String, name As String, row As Integer, Optional value As String = "", Optional password As Boolean = False)
        layout.Controls.Add(New Label With {.Text = label, .AutoSize = True, .Anchor = AnchorStyles.Left}, 0, row)
        Dim entry = New TextBox With {.Dock = DockStyle.Fill, .Text = value, .UseSystemPasswordChar = password}
        layout.Controls.Add(entry, 1, row)
        _entries(name) = entry
    End Sub

    Private Sub Submit(sender As Object, eventArgs As EventArgs)
        If _entries.Values.Any(Function(entry) String.IsNullOrWhiteSpace(entry.Text)) Then
            MessageBox.Show(Me, "Enter all MySQL fields, PPC and CLN.", "Missing input", MessageBoxButtons.OK, MessageBoxIcon.Warning)
            Return
        End If
        Dim port As UInteger
        If Not UInteger.TryParse(_entries("port").Text, port) Then
            MessageBox.Show(Me, "MySQL Port must be a number.", "Invalid port", MessageBoxButtons.OK, MessageBoxIcon.Warning)
            Return
        End If
        Settings.Host = _entries("host").Text.Trim()
        Settings.Port = port
        Settings.DatabaseName = _entries("database").Text.Trim()
        Settings.UserName = _entries("username").Text.Trim()
        Settings.Password = _entries("password").Text
        ProductionPlaceCode = _entries("ppc").Text.Trim()
        CoatLotNumber = _entries("cln").Text.Trim()
        DialogResult = DialogResult.OK
        Close()
    End Sub
End Class

Public NotInheritable Class HeaderEditDialog
    Inherits Form

    Private ReadOnly _item As New TextBox()
    Private ReadOnly _plate As New TextBox()
    Private ReadOnly _dateTime As New TextBox()
    Private ReadOnly _capa As New TextBox()
    Private ReadOnly _dome As New TextBox()
    Private ReadOnly _longtail83 As New TextBox()
    Private ReadOnly _longtail95 As New TextBox()
    Private ReadOnly _coatLot As New TextBox()
    Private ReadOnly _operator As New TextBox()
    Private ReadOnly _startTray As New NumericUpDown()

    Public ReadOnly Property ItemValue As String
        Get
            Return _item.Text
        End Get
    End Property

    Public ReadOnly Property PlateNoValue As String
        Get
            Return _plate.Text
        End Get
    End Property

    Public ReadOnly Property DateTimeValue As String
        Get
            Return _dateTime.Text
        End Get
    End Property

    Public ReadOnly Property CapaValue As String
        Get
            Return _capa.Text
        End Get
    End Property

    Public ReadOnly Property DomeTypeValue As String
        Get
            Return _dome.Text
        End Get
    End Property

    Public ReadOnly Property Longtail83Value As String
        Get
            Return _longtail83.Text
        End Get
    End Property

    Public ReadOnly Property Longtail95Value As String
        Get
            Return _longtail95.Text
        End Get
    End Property

    Public ReadOnly Property CoatLotValue As String
        Get
            Return _coatLot.Text
        End Get
    End Property

    Public ReadOnly Property OperatorValue As String
        Get
            Return _operator.Text.Trim()
        End Get
    End Property

    Public ReadOnly Property StartTrayPositionValue As Integer
        Get
            Return CInt(_startTray.Value)
        End Get
    End Property

    Public Sub New(sheet As SheetData)
        Text = "Edit Report Header"
        StartPosition = FormStartPosition.CenterParent
        FormBorderStyle = FormBorderStyle.FixedDialog
        ClientSize = New Size(460, 405)
        Dim layout As New TableLayoutPanel With {.Dock = DockStyle.Fill, .Padding = New Padding(16), .ColumnCount = 2, .RowCount = 11}
        layout.ColumnStyles.Add(New ColumnStyle(SizeType.Absolute, 140))
        layout.ColumnStyles.Add(New ColumnStyle(SizeType.Percent, 100))
        Controls.Add(layout)
        AddField(layout, "ITEM", _item, sheet.Item, 0)
        AddField(layout, "PLATE No.", _plate, sheet.PlateNo, 1)
        AddField(layout, "DATETIME", _dateTime, sheet.DateTimeStamp, 2)
        AddField(layout, "CAPA.", _capa, sheet.Capa, 3)
        AddField(layout, "DOME Type", _dome, sheet.DomeType, 4)
        AddField(layout, "Longtail 83", _longtail83, sheet.Longtail83, 5)
        AddField(layout, "Longtail 95", _longtail95, sheet.Longtail95, 6)
        AddField(layout, "Coat Lot No.", _coatLot, sheet.CoatLotNo, 7)
        AddField(layout, "Operator", _operator, sheet.OperatorName, 8)
        AddNumber(layout, "Start T-*", _startTray, sheet.StartTrayPosition, 9)
        Dim save = New Button With {.Text = "Save", .DialogResult = DialogResult.OK}
        AddHandler save.Click, AddressOf Submit
        layout.Controls.Add(save, 1, 10)
        AcceptButton = save
    End Sub

    Private Shared Sub AddField(layout As TableLayoutPanel, label As String, entry As TextBox, value As String, row As Integer)
        layout.Controls.Add(New Label With {.Text = label, .AutoSize = True}, 0, row)
        entry.Text = value
        entry.Dock = DockStyle.Fill
        layout.Controls.Add(entry, 1, row)
    End Sub

    Private Shared Sub AddNumber(layout As TableLayoutPanel, label As String, entry As NumericUpDown, value As Integer, row As Integer)
        layout.Controls.Add(New Label With {.Text = label, .AutoSize = True}, 0, row)
        entry.Minimum = 1
        entry.Maximum = 999
        entry.Value = Math.Clamp(value, 1, 999)
        entry.Dock = DockStyle.Fill
        layout.Controls.Add(entry, 1, row)
    End Sub

    Private Sub Submit(sender As Object, eventArgs As EventArgs)
        If String.IsNullOrWhiteSpace(_operator.Text) Then
            MessageBox.Show(Me, "Enter Operator before saving.", "Missing Operator", MessageBoxButtons.OK, MessageBoxIcon.Warning)
            DialogResult = DialogResult.None
        End If
    End Sub
End Class

Public NotInheritable Class StartupSetupDialog
    Inherits Form

    Private ReadOnly _operator As New TextBox()
    Private ReadOnly _startTray As New NumericUpDown()

    Public ReadOnly Property OperatorNameValue As String
        Get
            Return _operator.Text.Trim()
        End Get
    End Property

    Public ReadOnly Property StartTrayPositionValue As Integer
        Get
            Return CInt(_startTray.Value)
        End Get
    End Property

    Public Sub New()
        Text = "Report setup"
        StartPosition = FormStartPosition.CenterParent
        FormBorderStyle = FormBorderStyle.FixedDialog
        MaximizeBox = False
        MinimizeBox = False
        ClientSize = New Size(390, 170)

        Dim layout As New TableLayoutPanel With {.Dock = DockStyle.Fill, .Padding = New Padding(16), .ColumnCount = 2, .RowCount = 3}
        layout.ColumnStyles.Add(New ColumnStyle(SizeType.Absolute, 130))
        layout.ColumnStyles.Add(New ColumnStyle(SizeType.Percent, 100))
        Controls.Add(layout)

        layout.Controls.Add(New Label With {.Text = "Operator", .AutoSize = True}, 0, 0)
        _operator.Dock = DockStyle.Fill
        layout.Controls.Add(_operator, 1, 0)

        layout.Controls.Add(New Label With {.Text = "Start T-*", .AutoSize = True}, 0, 1)
        _startTray.Minimum = 1
        _startTray.Maximum = 999
        _startTray.Value = 1
        _startTray.Dock = DockStyle.Fill
        layout.Controls.Add(_startTray, 1, 1)

        Dim buttons As New FlowLayoutPanel With {.Dock = DockStyle.Fill, .FlowDirection = FlowDirection.RightToLeft}
        Dim ok = New Button With {.Text = "Start", .DialogResult = DialogResult.OK}
        AddHandler ok.Click, AddressOf Submit
        buttons.Controls.Add(ok)
        buttons.Controls.Add(New Button With {.Text = "Cancel", .DialogResult = DialogResult.Cancel})
        layout.Controls.Add(buttons, 0, 2)
        layout.SetColumnSpan(buttons, 2)
        AcceptButton = ok
        CancelButton = buttons.Controls.OfType(Of Button)().Last()
    End Sub

    Private Sub Submit(sender As Object, eventArgs As EventArgs)
        If String.IsNullOrWhiteSpace(_operator.Text) Then
            MessageBox.Show(Me, "Enter Operator before continuing.", "Missing Operator", MessageBoxButtons.OK, MessageBoxIcon.Warning)
            DialogResult = DialogResult.None
        End If
    End Sub
End Class

Public NotInheritable Class StartTrayDialog
    Inherits Form

    Private ReadOnly _startTray As New NumericUpDown()

    Public ReadOnly Property StartTrayPositionValue As Integer
        Get
            Return CInt(_startTray.Value)
        End Get
    End Property

    Public Sub New(currentStartTray As Integer)
        Text = "Adjust data start T"
        StartPosition = FormStartPosition.CenterParent
        FormBorderStyle = FormBorderStyle.FixedDialog
        MaximizeBox = False
        MinimizeBox = False
        ClientSize = New Size(420, 155)

        Dim layout As New TableLayoutPanel With {.Dock = DockStyle.Fill, .Padding = New Padding(16), .ColumnCount = 2, .RowCount = 3}
        layout.ColumnStyles.Add(New ColumnStyle(SizeType.Absolute, 140))
        layout.ColumnStyles.Add(New ColumnStyle(SizeType.Percent, 100))
        Controls.Add(layout)

        layout.Controls.Add(New Label With {
            .Text = "Data starts at T-*",
            .AutoSize = True
        }, 0, 0)
        _startTray.Minimum = 1
        _startTray.Maximum = 999
        _startTray.Value = Math.Clamp(currentStartTray, 1, 999)
        _startTray.Dock = DockStyle.Fill
        layout.Controls.Add(_startTray, 1, 0)

        Dim note As New Label With {
            .Text = "This moves imported data only. Printed T-1..T-22 positions stay fixed.",
            .AutoSize = True,
            .ForeColor = Color.DarkSlateGray
        }
        layout.Controls.Add(note, 0, 1)
        layout.SetColumnSpan(note, 2)

        Dim buttons As New FlowLayoutPanel With {.Dock = DockStyle.Fill, .FlowDirection = FlowDirection.RightToLeft}
        buttons.Controls.Add(New Button With {.Text = "Apply", .DialogResult = DialogResult.OK})
        buttons.Controls.Add(New Button With {.Text = "Cancel", .DialogResult = DialogResult.Cancel})
        layout.Controls.Add(buttons, 0, 2)
        layout.SetColumnSpan(buttons, 2)
        AcceptButton = buttons.Controls.OfType(Of Button)().First()
        CancelButton = buttons.Controls.OfType(Of Button)().Last()
    End Sub
End Class

Public NotInheritable Class TrayLotEditDialog
    Inherits Form

    Private ReadOnly _lot As New TextBox()

    Public ReadOnly Property LotNumberValue As String
        Get
            Return _lot.Text.Trim()
        End Get
    End Property

    Public Sub New(trayLabel As Integer, currentLot As String)
        Text = $"Edit T-{trayLabel} Dip Lot"
        StartPosition = FormStartPosition.CenterParent
        FormBorderStyle = FormBorderStyle.FixedDialog
        MaximizeBox = False
        MinimizeBox = False
        ClientSize = New Size(380, 150)

        Dim layout As New TableLayoutPanel With {.Dock = DockStyle.Fill, .Padding = New Padding(16), .ColumnCount = 2, .RowCount = 3}
        layout.ColumnStyles.Add(New ColumnStyle(SizeType.Absolute, 120))
        layout.ColumnStyles.Add(New ColumnStyle(SizeType.Percent, 100))
        Controls.Add(layout)

        Dim heading As New Label With {
            .Text = $"T-{trayLabel}",
            .AutoSize = True,
            .Font = New Font("Segoe UI", 11, FontStyle.Bold)
        }
        layout.Controls.Add(heading, 0, 0)
        layout.SetColumnSpan(heading, 2)

        layout.Controls.Add(New Label With {.Text = "Dip Lot", .AutoSize = True, .Anchor = AnchorStyles.Left}, 0, 1)
        _lot.Text = currentLot
        _lot.Dock = DockStyle.Fill
        layout.Controls.Add(_lot, 1, 1)

        Dim buttons As New FlowLayoutPanel With {.Dock = DockStyle.Fill, .FlowDirection = FlowDirection.RightToLeft}
        Dim save = New Button With {.Text = "Save", .DialogResult = DialogResult.OK}
        buttons.Controls.Add(save)
        buttons.Controls.Add(New Button With {.Text = "Cancel", .DialogResult = DialogResult.Cancel})
        layout.Controls.Add(buttons, 0, 2)
        layout.SetColumnSpan(buttons, 2)
        AcceptButton = save
        CancelButton = buttons.Controls.OfType(Of Button)().Last()
    End Sub
End Class

Public NotInheritable Class OperatorEditDialog
    Inherits Form

    Private ReadOnly _operator As New TextBox()

    Public ReadOnly Property OperatorNameValue As String
        Get
            Return _operator.Text.Trim()
        End Get
    End Property

    Public Sub New(currentOperator As String)
        Text = "Edit Operator"
        StartPosition = FormStartPosition.CenterParent
        FormBorderStyle = FormBorderStyle.FixedDialog
        MaximizeBox = False
        MinimizeBox = False
        ClientSize = New Size(380, 150)

        Dim layout As New TableLayoutPanel With {.Dock = DockStyle.Fill, .Padding = New Padding(16), .ColumnCount = 2, .RowCount = 2}
        layout.ColumnStyles.Add(New ColumnStyle(SizeType.Absolute, 120))
        layout.ColumnStyles.Add(New ColumnStyle(SizeType.Percent, 100))
        Controls.Add(layout)

        layout.Controls.Add(New Label With {.Text = "Operator", .AutoSize = True, .Anchor = AnchorStyles.Left}, 0, 0)
        _operator.Text = currentOperator
        _operator.Dock = DockStyle.Fill
        layout.Controls.Add(_operator, 1, 0)

        Dim buttons As New FlowLayoutPanel With {.Dock = DockStyle.Fill, .FlowDirection = FlowDirection.RightToLeft}
        Dim save = New Button With {.Text = "Save", .DialogResult = DialogResult.OK}
        AddHandler save.Click, AddressOf Submit
        buttons.Controls.Add(save)
        buttons.Controls.Add(New Button With {.Text = "Cancel", .DialogResult = DialogResult.Cancel})
        layout.Controls.Add(buttons, 0, 1)
        layout.SetColumnSpan(buttons, 2)
        AcceptButton = save
        CancelButton = buttons.Controls.OfType(Of Button)().Last()
    End Sub

    Private Sub Submit(sender As Object, eventArgs As EventArgs)
        If String.IsNullOrWhiteSpace(_operator.Text) Then
            MessageBox.Show(Me, "Enter Operator before saving.", "Missing Operator", MessageBoxButtons.OK, MessageBoxIcon.Warning)
            DialogResult = DialogResult.None
        End If
    End Sub
End Class

Public NotInheritable Class CellEditDialog
    Inherits Form

    Private ReadOnly _mode As New ComboBox()
    Private ReadOnly _diameter As New TextBox()
    Private ReadOnly _trayNumber As New TextBox()
    Private ReadOnly _lotNumber As New TextBox()

    Public ReadOnly Property DisplayModeValue As String
        Get
            Return CStr(_mode.SelectedItem)
        End Get
    End Property

    Public ReadOnly Property DiameterValue As Double
        Get
            Dim value As Double
            Double.TryParse(_diameter.Text.Trim(), NumberStyles.Number, CultureInfo.InvariantCulture, value)
            Return value
        End Get
    End Property

    Public ReadOnly Property TrayNumberValue As String
        Get
            Return _trayNumber.Text.Trim()
        End Get
    End Property

    Public ReadOnly Property LotNumberValue As String
        Get
            Return _lotNumber.Text.Trim()
        End Get
    End Property

    Public Sub New(hit As ReportCellHit, measurement As Measurement)
        Text = $"Edit T-{hit.TrayLabel} Row {hit.RowNumber} {hit.Side}"
        StartPosition = FormStartPosition.CenterParent
        FormBorderStyle = FormBorderStyle.FixedDialog
        MaximizeBox = False
        MinimizeBox = False
        ClientSize = New Size(430, 245)

        Dim layout As New TableLayoutPanel With {
            .Dock = DockStyle.Fill,
            .Padding = New Padding(16),
            .ColumnCount = 2,
            .RowCount = 6
        }
        layout.ColumnStyles.Add(New ColumnStyle(SizeType.Absolute, 130))
        layout.ColumnStyles.Add(New ColumnStyle(SizeType.Percent, 100))
        Controls.Add(layout)

        Dim heading As New Label With {
            .Text = $"T-{hit.TrayLabel} / Row {hit.RowNumber} / {hit.Side}",
            .AutoSize = True,
            .Font = New Font("Segoe UI", 11, FontStyle.Bold)
        }
        layout.Controls.Add(heading, 0, 0)
        layout.SetColumnSpan(heading, 2)

        _mode.DropDownStyle = ComboBoxStyle.DropDownList
        _mode.Items.AddRange({"Value", "Dash (-)", "Blank"})
        _mode.SelectedItem = CurrentMode(hit.Side, measurement)
        AddField(layout, "Display", _mode, 1)

        _diameter.Text = CurrentDiameter(hit.Side, measurement)
        AddField(layout, "Diameter", _diameter, 2)

        _trayNumber.Text = If(measurement Is Nothing, "", measurement.TrayNumber)
        AddField(layout, "Tray Number", _trayNumber, 3)

        _lotNumber.Text = If(measurement Is Nothing, "", measurement.LotNumber)
        AddField(layout, "Dip Lot", _lotNumber, 4)

        Dim buttons As New FlowLayoutPanel With {.Dock = DockStyle.Fill, .FlowDirection = FlowDirection.RightToLeft}
        Dim save = New Button With {.Text = "Save", .DialogResult = DialogResult.OK}
        AddHandler save.Click, AddressOf Submit
        buttons.Controls.Add(save)
        buttons.Controls.Add(New Button With {.Text = "Cancel", .DialogResult = DialogResult.Cancel})
        layout.Controls.Add(buttons, 0, 5)
        layout.SetColumnSpan(buttons, 2)

        AddHandler _mode.SelectedIndexChanged, Sub() UpdateDiameterState()
        UpdateDiameterState()
        AcceptButton = save
        CancelButton = buttons.Controls.OfType(Of Button)().Last()
    End Sub

    Private Shared Sub AddField(layout As TableLayoutPanel, label As String, control As Control, row As Integer)
        layout.Controls.Add(New Label With {.Text = label, .AutoSize = True, .Anchor = AnchorStyles.Left}, 0, row)
        control.Dock = DockStyle.Fill
        layout.Controls.Add(control, 1, row)
    End Sub

    Private Shared Function CurrentMode(side As String, measurement As Measurement) As String
        If measurement Is Nothing Then Return "Blank"
        If side = "R" Then
            If measurement.RDash Then Return "Dash (-)"
            If measurement.RPresent Then Return "Value"
            Return "Blank"
        End If
        If measurement.LDash Then Return "Dash (-)"
        If measurement.LPresent Then Return "Value"
        Return "Blank"
    End Function

    Private Shared Function CurrentDiameter(side As String, measurement As Measurement) As String
        If measurement Is Nothing Then Return ""
        Dim value = If(side = "R", measurement.RDiameter, measurement.LDiameter)
        If value = 0 Then Return ""
        Return Math.Round(value).ToString(CultureInfo.InvariantCulture)
    End Function

    Private Sub UpdateDiameterState()
        _diameter.Enabled = DisplayModeValue = "Value"
    End Sub

    Private Sub Submit(sender As Object, eventArgs As EventArgs)
        If DisplayModeValue <> "Value" Then Return
        Dim value As Double
        If Not Double.TryParse(_diameter.Text.Trim(), NumberStyles.Number, CultureInfo.InvariantCulture, value) Then
            MessageBox.Show(Me, "Diameter must be a number.", "Invalid Diameter", MessageBoxButtons.OK, MessageBoxIcon.Warning)
            DialogResult = DialogResult.None
        End If
    End Sub
End Class

Public NotInheritable Class EditLogViewerDialog
    Inherits Form

    Private Const AllDates As String = "All dates"
    Private Const DateFormat As String = "yyyy-MM-dd"

    Private ReadOnly _store As EditLogStore
    Private ReadOnly _grid As New DataGridView()
    Private ReadOnly _empty As New Label()
    Private ReadOnly _count As New Label()
    Private ReadOnly _dateFilter As New ComboBox()
    Private _allEntries As New List(Of EditLogEntry)

    Public Sub New(store As EditLogStore)
        _store = store
        Text = "Edit Log"
        StartPosition = FormStartPosition.CenterParent
        FormBorderStyle = FormBorderStyle.Sizable
        MinimizeBox = False
        ClientSize = New Size(920, 500)
        MinimumSize = New Size(680, 380)

        _grid.Dock = DockStyle.Fill
        _grid.ReadOnly = True
        _grid.AllowUserToAddRows = False
        _grid.AllowUserToDeleteRows = False
        _grid.AllowUserToResizeRows = False
        _grid.RowHeadersVisible = False
        _grid.SelectionMode = DataGridViewSelectionMode.FullRowSelect
        _grid.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill
        _grid.BackgroundColor = Color.White
        _grid.BorderStyle = BorderStyle.None
        _grid.EnableHeadersVisualStyles = False
        _grid.ColumnHeadersDefaultCellStyle.Font = New Font("Segoe UI", 9, FontStyle.Bold)
        AddColumn("Timestamp", 16)
        AddColumn("Operator", 14)
        AddColumn("Target", 22)
        AddColumn("Field", 14)
        AddColumn("Before", 17)
        AddColumn("After", 17)

        _empty.Text = "No edits have been logged yet."
        _empty.Dock = DockStyle.Fill
        _empty.TextAlign = ContentAlignment.MiddleCenter
        _empty.ForeColor = Color.DimGray
        _empty.Font = New Font("Segoe UI", 11)
        _empty.Visible = False

        Dim filterBar As New FlowLayoutPanel With {
            .Dock = DockStyle.Top,
            .FlowDirection = FlowDirection.LeftToRight,
            .Height = 44,
            .Padding = New Padding(8, 10, 8, 8),
            .BackColor = Color.White
        }
        filterBar.Controls.Add(New Label With {
            .Text = "Show log for date:",
            .AutoSize = True,
            .Margin = New Padding(2, 6, 6, 0)
        })
        _dateFilter.DropDownStyle = ComboBoxStyle.DropDownList
        _dateFilter.Width = 160
        AddHandler _dateFilter.SelectedIndexChanged, AddressOf OnDateFilterChanged
        filterBar.Controls.Add(_dateFilter)

        Dim buttons As New FlowLayoutPanel With {
            .Dock = DockStyle.Bottom,
            .FlowDirection = FlowDirection.RightToLeft,
            .Height = 50,
            .Padding = New Padding(8)
        }
        Dim closeButton = New Button With {.Text = "Close", .DialogResult = DialogResult.Cancel, .AutoSize = True}
        Dim exportButton = New Button With {.Text = "Export to Excel", .AutoSize = True}
        AddHandler exportButton.Click, AddressOf ExportXlsx
        Dim refreshButton = New Button With {.Text = "Refresh", .AutoSize = True}
        AddHandler refreshButton.Click, Sub() LoadEntries()
        buttons.Controls.Add(closeButton)
        buttons.Controls.Add(exportButton)
        buttons.Controls.Add(refreshButton)

        _count.AutoSize = True
        _count.Anchor = AnchorStyles.Left
        _count.Margin = New Padding(10, 14, 0, 0)
        _count.ForeColor = Color.DimGray
        buttons.Controls.Add(_count)

        Controls.Add(_grid)
        Controls.Add(_empty)
        Controls.Add(filterBar)
        Controls.Add(buttons)
        CancelButton = closeButton

        LoadEntries()
    End Sub

    Private Sub AddColumn(title As String, fillWeight As Integer)
        Dim column As New DataGridViewTextBoxColumn With {
            .Name = title,
            .HeaderText = title,
            .FillWeight = fillWeight,
            .SortMode = DataGridViewColumnSortMode.NotSortable
        }
        _grid.Columns.Add(column)
    End Sub

    Private Sub LoadEntries()
        _allEntries = _store.ReadAll().OrderByDescending(Function(entry) entry.Timestamp).ToList()
        PopulateDateFilter()
        ApplyFilter()
    End Sub

    ' Rebuild the day list from whatever is in the log, keeping the operator's current
    ' choice selected when that day still exists.
    Private Sub PopulateDateFilter()
        Dim selected = TryCast(_dateFilter.SelectedItem, String)
        RemoveHandler _dateFilter.SelectedIndexChanged, AddressOf OnDateFilterChanged
        _dateFilter.Items.Clear()
        _dateFilter.Items.Add(AllDates)
        For Each day In _allEntries.Select(Function(entry) entry.Timestamp.Date).Distinct().OrderByDescending(Function(d) d)
            _dateFilter.Items.Add(day.ToString(DateFormat, CultureInfo.InvariantCulture))
        Next
        Dim index = If(selected Is Nothing, -1, _dateFilter.Items.IndexOf(selected))
        _dateFilter.SelectedIndex = If(index < 0, 0, index)
        AddHandler _dateFilter.SelectedIndexChanged, AddressOf OnDateFilterChanged
    End Sub

    Private Sub OnDateFilterChanged(sender As Object, eventArgs As EventArgs)
        ApplyFilter()
    End Sub

    Private Function CurrentView() As List(Of EditLogEntry)
        Dim selected = TryCast(_dateFilter.SelectedItem, String)
        If selected Is Nothing OrElse selected = AllDates Then Return _allEntries
        Return _allEntries.
            Where(Function(entry) entry.Timestamp.ToString(DateFormat, CultureInfo.InvariantCulture) = selected).
            ToList()
    End Function

    Private Sub ApplyFilter()
        Dim view = CurrentView()
        _grid.Rows.Clear()
        For Each entry In view
            _grid.Rows.Add(
                entry.Timestamp.ToString("yyyy-MM-dd HH:mm:ss", CultureInfo.InvariantCulture),
                entry.OperatorName,
                entry.Target,
                entry.Field,
                entry.OldValue,
                entry.NewValue
            )
        Next
        _grid.Visible = view.Count > 0
        _empty.Visible = view.Count = 0
        _count.Text = $"{view.Count} edit(s) logged"
    End Sub

    Private Sub ExportXlsx(sender As Object, eventArgs As EventArgs)
        Dim view = CurrentView()
        If view.Count = 0 Then
            MessageBox.Show(Me, "There are no log entries to export.", "Export Edit Log", MessageBoxButtons.OK, MessageBoxIcon.Information)
            Return
        End If
        Dim selected = TryCast(_dateFilter.SelectedItem, String)
        Dim suffix = If(selected Is Nothing OrElse selected = AllDates, "AllDates", selected)
        Using dialog As New SaveFileDialog With {
            .Title = "Export edit log to Excel",
            .Filter = "Excel workbook (*.xlsx)|*.xlsx",
            .FileName = $"EditLog_{suffix}.xlsx"
        }
            If dialog.ShowDialog(Me) <> DialogResult.OK Then Return
            Try
                _store.ExportToXlsx(dialog.FileName, view)
                MessageBox.Show(Me, "Edit log exported to Excel.", "Export Edit Log", MessageBoxButtons.OK, MessageBoxIcon.Information)
            Catch ex As Exception
                MessageBox.Show(Me, ex.Message, "Export Edit Log failed", MessageBoxButtons.OK, MessageBoxIcon.Error)
            End Try
        End Using
    End Sub
End Class

