Option Strict On
Option Explicit On

Imports AutoGenerateDiameter.Core
Imports System.ComponentModel

Public NotInheritable Class DatabaseLoadDialog
    Inherits Form

    Private ReadOnly _entries As New Dictionary(Of String, TextBox)
    Public ReadOnly Property Settings As New MySqlConnectionSettings()
    Public Property ProductionPlaceCode As String = ""
    Public Property CoatLotNumber As String = ""

    Public Sub New()
        Text = "Load from Database"
        FormBorderStyle = FormBorderStyle.FixedDialog
        StartPosition = FormStartPosition.CenterParent
        MaximizeBox = False
        MinimizeBox = False
        ClientSize = New Size(430, 410)

        Dim layout As New TableLayoutPanel With {
            .Dock = DockStyle.Fill,
            .Padding = New Padding(18),
            .ColumnCount = 2,
            .RowCount = 10
        }
        layout.ColumnStyles.Add(New ColumnStyle(SizeType.Absolute, 180))
        layout.ColumnStyles.Add(New ColumnStyle(SizeType.Percent, 100))
        Controls.Add(layout)

        AddHeading(layout, "MySQL Connection", 0)
        AddField(layout, "MySQL Host", "host", 1)
        AddField(layout, "MySQL Port", "port", 2, "3306")
        AddField(layout, "Database", "database", 3)
        AddField(layout, "Username", "username", 4)
        AddField(layout, "Password", "password", 5, password:=True)
        AddHeading(layout, "Report Criteria", 6)
        AddField(layout, "PPC", "ppc", 7)
        AddField(layout, "CLN", "cln", 8)

        Dim buttons As New FlowLayoutPanel With {.Dock = DockStyle.Fill, .FlowDirection = FlowDirection.RightToLeft}
        Dim load = New Button With {.Text = "Load", .DialogResult = DialogResult.None}
        AddHandler load.Click, AddressOf Submit
        buttons.Controls.Add(load)
        buttons.Controls.Add(New Button With {.Text = "Cancel", .DialogResult = DialogResult.Cancel})
        layout.Controls.Add(buttons, 0, 9)
        layout.SetColumnSpan(buttons, 2)
        AcceptButton = load
        CancelButton = buttons.Controls.OfType(Of Button)().Last()
    End Sub

    Private Shared Sub AddHeading(layout As TableLayoutPanel, text As String, row As Integer)
        Dim label = New Label With {.Text = text, .AutoSize = True, .Font = New Font("Segoe UI", 11, FontStyle.Bold)}
        layout.Controls.Add(label, 0, row)
        layout.SetColumnSpan(label, 2)
    End Sub

    Private Sub AddField(layout As TableLayoutPanel, label As String, name As String, row As Integer, Optional value As String = "", Optional password As Boolean = False)
        layout.Controls.Add(New Label With {.Text = label, .AutoSize = True, .Anchor = AnchorStyles.Left}, 0, row)
        Dim entry = New TextBox With {.Dock = DockStyle.Fill, .Text = value, .UseSystemPasswordChar = password}
        layout.Controls.Add(entry, 1, row)
        _entries(name) = entry
    End Sub

    Private Sub Submit(sender As Object, eventArgs As EventArgs)
        If _entries.Values.Any(Function(entry) String.IsNullOrWhiteSpace(entry.Text)) Then
            MessageBox.Show(Me, "Enter all MySQL fields, PPC and CLN.", "Missing input", MessageBoxButtons.OK, MessageBoxIcon.Warning)
            Return
        End If
        Dim port As UInteger
        If Not UInteger.TryParse(_entries("port").Text, port) Then
            MessageBox.Show(Me, "MySQL Port must be a number.", "Invalid port", MessageBoxButtons.OK, MessageBoxIcon.Warning)
            Return
        End If
        Settings.Host = _entries("host").Text.Trim()
        Settings.Port = port
        Settings.DatabaseName = _entries("database").Text.Trim()
        Settings.UserName = _entries("username").Text.Trim()
        Settings.Password = _entries("password").Text
        ProductionPlaceCode = _entries("ppc").Text.Trim()
        CoatLotNumber = _entries("cln").Text.Trim()
        DialogResult = DialogResult.OK
        Close()
    End Sub
End Class

Public NotInheritable Class ManualImageImportDialog
    Inherits Form

    Private ReadOnly _item As New TextBox()
    Private ReadOnly _plate As New TextBox()
    Private ReadOnly _dateTime As New TextBox()
    Private ReadOnly _dome As New TextBox()
    Private ReadOnly _capa As New TextBox()
    Private ReadOnly _coatLot As New TextBox()
    Private ReadOnly _longtail83 As New NumericUpDown()
    Private ReadOnly _longtail95 As New NumericUpDown()
    Private ReadOnly _grid As New DataGridView()

    Public ReadOnly Property ItemValue As String
        Get
            Return _item.Text
        End Get
    End Property

    Public ReadOnly Property PlateNoValue As String
        Get
            Return _plate.Text
        End Get
    End Property

    Public ReadOnly Property DateTimeValue As String
        Get
            Return _dateTime.Text
        End Get
    End Property

    Public ReadOnly Property DomeTypeValue As String
        Get
            Return _dome.Text
        End Get
    End Property

    Public ReadOnly Property CapaValue As String
        Get
            Return _capa.Text
        End Get
    End Property

    Public ReadOnly Property CoatLotValue As String
        Get
            Return _coatLot.Text
        End Get
    End Property

    Public ReadOnly Property Longtail83Value As Integer
        Get
            Return CInt(_longtail83.Value)
        End Get
    End Property

    Public ReadOnly Property Longtail95Value As Integer
        Get
            Return CInt(_longtail95.Value)
        End Get
    End Property

    Public Sub New(result As ManualImageImportResult)
        Text = "Review Manual Image OCR"
        StartPosition = FormStartPosition.CenterParent
        ClientSize = New Size(980, 720)

        Dim header As New TableLayoutPanel With {
            .Dock = DockStyle.Top,
            .Height = 58,
            .Padding = New Padding(12),
            .ColumnCount = 1,
            .RowCount = 1
        }
        header.ColumnStyles.Add(New ColumnStyle(SizeType.Percent, 100))
        header.Controls.Add(New Label With {
            .Text = $"OCR detected {result.DetectedWordCount} numeric words. Verify rows here. Header values are entered later with Edit Header.",
            .AutoSize = True,
            .ForeColor = Color.DarkRed
        }, 0, 0)

        _grid.Dock = DockStyle.Fill
        _grid.AutoGenerateColumns = False
        _grid.AllowUserToAddRows = True
        _grid.AllowUserToDeleteRows = True
        _grid.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill
        _grid.Columns.Add(New DataGridViewTextBoxColumn With {.HeaderText = "T Position", .DataPropertyName = "TrayPosition"})
        _grid.Columns.Add(New DataGridViewTextBoxColumn With {.HeaderText = "Row", .DataPropertyName = "RowNumber"})
        _grid.Columns.Add(New DataGridViewTextBoxColumn With {.HeaderText = "Dip Lot", .DataPropertyName = "DipLotNumber"})
        _grid.Columns.Add(New DataGridViewTextBoxColumn With {.HeaderText = "R Diameter", .DataPropertyName = "RDiameter"})
        _grid.Columns.Add(New DataGridViewTextBoxColumn With {.HeaderText = "L Diameter", .DataPropertyName = "LDiameter"})
        _grid.DataSource = result.Rows

        Dim buttons As New FlowLayoutPanel With {
            .Dock = DockStyle.Bottom,
            .Height = 50,
            .Padding = New Padding(8),
            .FlowDirection = FlowDirection.RightToLeft
        }
        Dim importButton = New Button With {.Text = "Import Reviewed Data", .AutoSize = True}
        AddHandler importButton.Click, AddressOf Submit
        buttons.Controls.Add(importButton)
        buttons.Controls.Add(New Button With {.Text = "Cancel", .DialogResult = DialogResult.Cancel})

        Controls.Add(_grid)
        Controls.Add(header)
        Controls.Add(buttons)
        AcceptButton = importButton
    End Sub

    Private Shared Sub AddReviewField(layout As TableLayoutPanel, label As String, entry As TextBox, row As Integer, column As Integer)
        layout.Controls.Add(New Label With {.Text = label, .AutoSize = True, .Anchor = AnchorStyles.Left}, column, row)
        entry.Dock = DockStyle.Fill
        layout.Controls.Add(entry, column + 1, row)
    End Sub

    Private Shared Sub AddReviewNumber(layout As TableLayoutPanel, label As String, entry As NumericUpDown, row As Integer, column As Integer)
        layout.Controls.Add(New Label With {.Text = label, .AutoSize = True, .Anchor = AnchorStyles.Left}, column, row)
        entry.Minimum = 0
        entry.Maximum = 999
        entry.Dock = DockStyle.Fill
        layout.Controls.Add(entry, column + 1, row)
    End Sub

    Private Sub Submit(sender As Object, eventArgs As EventArgs)
        _grid.EndEdit()
        Dim rows = DirectCast(_grid.DataSource, BindingList(Of ManualImportRow))
        If rows.Count = 0 OrElse Not rows.Any(Function(row) Not String.IsNullOrWhiteSpace(row.RDiameter) OrElse Not String.IsNullOrWhiteSpace(row.LDiameter)) Then
            MessageBox.Show(Me, "Add or keep at least one diameter value.", "No data", MessageBoxButtons.OK, MessageBoxIcon.Warning)
            Return
        End If
        DialogResult = DialogResult.OK
        Close()
    End Sub
End Class

Public NotInheritable Class ManualCompareDialog
    Inherits Form

    Private ReadOnly _result As CompareResult
    Private ReadOnly _summary As New Label()
    Private ReadOnly _grid As New DataGridView()
    Private ReadOnly _compareBinding As New BindingSource()
    Private ReadOnly _imageView As New CompareImageView()
    Private ReadOnly _crop As New PictureBox()
    Private _allowClose As Boolean

    Public Sub New(result As CompareResult)
        _result = result
        Text = "Manual comparison"
        StartPosition = FormStartPosition.CenterParent
        ClientSize = New Size(1280, 780)
        MinimumSize = New Size(1050, 680)

        _summary = New Label With {
            .Dock = DockStyle.Top,
            .Height = 72,
            .Padding = New Padding(12, 10, 12, 8),
            .Font = New Font("Segoe UI", 12, FontStyle.Bold),
            .AutoEllipsis = True
        }
        UpdateSummary()

        _grid = New DataGridView With {
            .Dock = DockStyle.Fill,
            .ReadOnly = True,
            .AllowUserToAddRows = False,
            .AutoGenerateColumns = False,
            .AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill,
            .SelectionMode = DataGridViewSelectionMode.FullRowSelect,
            .MultiSelect = True
        }
        _grid.Columns.Add(New DataGridViewTextBoxColumn With {.HeaderText = "Category", .DataPropertyName = "Category"})
        _grid.Columns.Add(New DataGridViewTextBoxColumn With {.HeaderText = "Position", .DataPropertyName = "Position"})
        _grid.Columns.Add(New DataGridViewTextBoxColumn With {.HeaderText = "Expected", .DataPropertyName = "Value"})
        _grid.Columns.Add(New DataGridViewTextBoxColumn With {.HeaderText = "OCR", .DataPropertyName = "OcrValue"})
        _grid.Columns.Add(New DataGridViewTextBoxColumn With {.HeaderText = "Confidence", .DataPropertyName = "Confidence"})
        _grid.Columns.Add(New DataGridViewTextBoxColumn With {.HeaderText = "Result", .DataPropertyName = "Result"})
        _compareBinding.DataSource = result.Items
        _grid.DataSource = _compareBinding
        AddHandler _grid.SelectionChanged, AddressOf ShowSelectedItem
        AddHandler _grid.CellFormatting,
            Sub(sender, args)
                If args.RowIndex >= 0 Then
                    Dim item = result.Items(args.RowIndex)
                    If Not item.Comparable Then
                        _grid.Rows(args.RowIndex).DefaultCellStyle.ForeColor = Color.Gray
                    ElseIf item.Result = "MATCH" OrElse item.Result.Contains("CORRECT") OrElse item.Result = "MANUALLY CONFIRMED" Then
                        _grid.Rows(args.RowIndex).DefaultCellStyle.ForeColor = Color.Green
                    Else
                        _grid.Rows(args.RowIndex).DefaultCellStyle.ForeColor = Color.Red
                    End If
                End If
            End Sub

        _imageView.Dock = DockStyle.Fill
        _imageView.ImagePath = result.ImagePath
        _crop.Dock = DockStyle.Fill
        _crop.SizeMode = PictureBoxSizeMode.Zoom
        _crop.BackColor = Color.WhiteSmoke

        Dim images As New SplitContainer With {
            .Dock = DockStyle.Fill,
            .Orientation = Orientation.Horizontal,
            .SplitterDistance = 430
        }
        images.Panel1.Controls.Add(_imageView)
        images.Panel2.Controls.Add(_crop)

        Dim content As New SplitContainer With {.Dock = DockStyle.Fill, .SplitterDistance = 720}
        content.Panel1.Controls.Add(_grid)
        content.Panel2.Controls.Add(images)

        Dim reviewPanel As New TableLayoutPanel With {
            .Dock = DockStyle.Bottom,
            .Height = 62,
            .Padding = New Padding(10),
            .ColumnCount = 2
        }
        reviewPanel.ColumnStyles.Add(New ColumnStyle(SizeType.Percent, 100))
        reviewPanel.ColumnStyles.Add(New ColumnStyle(SizeType.Absolute, 170))
        Dim confirm = New Button With {.Text = "Confirm selected rows", .Dock = DockStyle.Fill}
        AddHandler confirm.Click, AddressOf ConfirmSelected
        reviewPanel.Controls.Add(confirm, 0, 0)
        Dim closeButton = New Button With {.Text = "Close", .Dock = DockStyle.Fill}
        AddHandler closeButton.Click, AddressOf CloseRequested
        reviewPanel.Controls.Add(closeButton, 1, 0)

        Controls.Add(content)
        Controls.Add(reviewPanel)
        Controls.Add(_summary)
        AddHandler FormClosing, AddressOf CheckBeforeClose
        AddHandler Shown, AddressOf ConfirmUnknownFormat
        ShowSelectedItem(Nothing, EventArgs.Empty)
    End Sub

    Private Sub ConfirmUnknownFormat(sender As Object, eventArgs As EventArgs)
        If _result.DetectedFormat <> "UNKNOWN" Then Return
        Using formatDialog As New ManualFormatDialog()
            formatDialog.ShowDialog(Me)
            _result.DetectedFormat = formatDialog.SelectedFormat
        End Using
        For Each item In _result.Items.Where(Function(value) value.Category = "Tray Lot" OrElse value.Category = "Tray Number")
            item.Comparable = _result.DetectedFormat = "NEW"
            item.Status = If(item.Comparable, If(item.OcrValue = "", "MISSING", "MATCH"), "NOT AVAILABLE")
        Next
        _compareBinding.ResetBindings(False)
        UpdateSummary()
    End Sub

    Private Sub UpdateSummary()
        _summary.Text = $"Manual Compare: {If(_result.Verified, "VERIFIED WITH MANUAL CONFIRMATION", "REVIEW REQUIRED")}   Format: {_result.DetectedFormat}" &
            Environment.NewLine &
            $"OCR Match: {_result.FoundCount}   Manual Confirmed: {_result.ManuallyConfirmedCount}   Pending: {_result.PendingCount}"
    End Sub

    Private Function SelectedItem() As CompareItem
        If _grid.CurrentRow Is Nothing Then Return Nothing
        Return TryCast(_grid.CurrentRow.DataBoundItem, CompareItem)
    End Function

    Private Sub ShowSelectedItem(sender As Object, eventArgs As EventArgs)
        Dim item = SelectedItem()
        _imageView.SelectedItem = item
        If _crop.Image IsNot Nothing Then
            _crop.Image.Dispose()
            _crop.Image = Nothing
        End If
        If item Is Nothing OrElse item.WidthRatio <= 0 OrElse String.IsNullOrWhiteSpace(_result.ImagePath) OrElse Not IO.File.Exists(_result.ImagePath) Then Return
        Using source = Image.FromFile(_result.ImagePath)
            Dim left = Math.Clamp(CInt(item.LeftRatio * source.Width), 0, source.Width - 1)
            Dim top = Math.Clamp(CInt(item.TopRatio * source.Height), 0, source.Height - 1)
            Dim width = Math.Clamp(CInt(item.WidthRatio * source.Width), 1, source.Width - left)
            Dim height = Math.Clamp(CInt(item.HeightRatio * source.Height), 1, source.Height - top)
            Dim bitmap As New Bitmap(width, height)
            Using cropGraphics = Graphics.FromImage(bitmap)
                cropGraphics.DrawImage(source, New Rectangle(0, 0, width, height), New Rectangle(left, top, width, height), GraphicsUnit.Pixel)
            End Using
            _crop.Image = bitmap
        End Using
    End Sub

    Private Sub ConfirmSelected(sender As Object, eventArgs As EventArgs)
        Dim selected = _grid.SelectedRows.
            Cast(Of DataGridViewRow)().
            Select(Function(row) TryCast(row.DataBoundItem, CompareItem)).
            Where(Function(item) item IsNot Nothing AndAlso item.Comparable AndAlso item.Status <> "MATCH").
            Cast(Of CompareItem)().
            ToList()
        If selected.Count = 0 Then Return
        For Each item In selected
            item.Resolution = "MANUALLY CONFIRMED"
            item.ConfirmedAt = DateTime.Now
        Next
        _compareBinding.ResetBindings(False)
        UpdateSummary()
        SelectNextPendingItem()
    End Sub

    Private Sub SelectNextPendingItem()
        If _grid.Rows.Count = 0 Then Return
        Dim startIndex = If(_grid.CurrentRow Is Nothing, -1, _grid.CurrentRow.Index)
        For offset = 1 To _grid.Rows.Count
            Dim index = (startIndex + offset) Mod _grid.Rows.Count
            Dim candidate = TryCast(_grid.Rows(index).DataBoundItem, CompareItem)
            If candidate IsNot Nothing AndAlso candidate.NeedsReview Then
                _grid.CurrentCell = _grid.Rows(index).Cells(0)
                Return
            End If
        Next
    End Sub

    Private Sub CloseRequested(sender As Object, eventArgs As EventArgs)
        Close()
    End Sub

    Private Sub CheckBeforeClose(sender As Object, eventArgs As FormClosingEventArgs)
        If _allowClose OrElse _result.PendingCount = 0 Then Return
        Dim choice = MessageBox.Show(
            Me,
            $"There are {_result.PendingCount} unresolved items." & Environment.NewLine &
            "You can continue without confirming all items. Close this window?",
            "Continue with pending items",
            MessageBoxButtons.YesNoCancel,
            MessageBoxIcon.Warning
        )
        If choice = DialogResult.Yes Then
            _allowClose = True
            Return
        End If
        eventArgs.Cancel = True
    End Sub
End Class

Public NotInheritable Class ManualFormatDialog
    Inherits Form

    Public Property SelectedFormat As String = "OLD"

    Public Sub New()
        Text = "Select manual sheet format"
        StartPosition = FormStartPosition.CenterParent
        FormBorderStyle = FormBorderStyle.FixedDialog
        MaximizeBox = False
        MinimizeBox = False
        ControlBox = False
        ClientSize = New Size(430, 155)

        Dim message As New Label With {
            .Dock = DockStyle.Top,
            .Height = 80,
            .Padding = New Padding(18),
            .Text = "Select the format used by this manual sheet:" & Environment.NewLine &
                "OLD: no Tray Lot / Tray Number   |   NEW: includes them",
            .Font = New Font("Segoe UI", 10)
        }
        Dim buttons As New FlowLayoutPanel With {
            .Dock = DockStyle.Fill,
            .FlowDirection = FlowDirection.LeftToRight,
            .Padding = New Padding(95, 12, 0, 0)
        }
        Dim oldButton As New Button With {.Text = "OLD", .Width = 110, .Height = 38}
        Dim newButton As New Button With {.Text = "NEW", .Width = 110, .Height = 38}
        AddHandler oldButton.Click,
            Sub()
                SelectedFormat = "OLD"
                DialogResult = DialogResult.OK
                Close()
            End Sub
        AddHandler newButton.Click,
            Sub()
                SelectedFormat = "NEW"
                DialogResult = DialogResult.OK
                Close()
            End Sub
        buttons.Controls.Add(oldButton)
        buttons.Controls.Add(newButton)
        Controls.Add(buttons)
        Controls.Add(message)
    End Sub
End Class

Public NotInheritable Class CompareImageView
    Inherits Control

    Private _image As Image
    Private _selectedItem As CompareItem

    Public Property ImagePath As String
        Set(value As String)
            If _image IsNot Nothing Then _image.Dispose()
            _image = Nothing
            If Not String.IsNullOrWhiteSpace(value) AndAlso IO.File.Exists(value) Then
                Using source = Image.FromFile(value)
                    _image = New Bitmap(source)
                End Using
            End If
            Invalidate()
        End Set
        Get
            Return ""
        End Get
    End Property

    Public Property SelectedItem As CompareItem
        Set(value As CompareItem)
            _selectedItem = value
            Invalidate()
        End Set
        Get
            Return _selectedItem
        End Get
    End Property

    Protected Overrides Sub OnPaint(e As PaintEventArgs)
        MyBase.OnPaint(e)
        e.Graphics.Clear(Color.FromArgb(235, 238, 242))
        If _image Is Nothing Then Return
        Dim scale = Math.Min(ClientSize.Width / CSng(_image.Width), ClientSize.Height / CSng(_image.Height))
        Dim width = CInt(_image.Width * scale)
        Dim height = CInt(_image.Height * scale)
        Dim x = (ClientSize.Width - width) \ 2
        Dim y = (ClientSize.Height - height) \ 2
        e.Graphics.DrawImage(_image, x, y, width, height)
        If _selectedItem Is Nothing OrElse _selectedItem.WidthRatio <= 0 Then Return
        Dim bounds As New RectangleF(
            CSng(x + _selectedItem.LeftRatio * width),
            CSng(y + _selectedItem.TopRatio * height),
            CSng(_selectedItem.WidthRatio * width),
            CSng(_selectedItem.HeightRatio * height)
        )
        Using pen As New Pen(Color.Red, 3)
            e.Graphics.DrawRectangle(pen, bounds.X, bounds.Y, bounds.Width, bounds.Height)
        End Using
    End Sub

    Protected Overrides Sub Dispose(disposing As Boolean)
        If disposing AndAlso _image IsNot Nothing Then _image.Dispose()
        MyBase.Dispose(disposing)
    End Sub
End Class

Public NotInheritable Class HeaderEditDialog
    Inherits Form

    Private ReadOnly _item As New TextBox()
    Private ReadOnly _plate As New TextBox()
    Private ReadOnly _dateTime As New TextBox()
    Private ReadOnly _capa As New TextBox()
    Private ReadOnly _dome As New TextBox()
    Private ReadOnly _longtail83 As New TextBox()
    Private ReadOnly _longtail95 As New TextBox()
    Private ReadOnly _coatLot As New TextBox()
    Private ReadOnly _operator As New TextBox()
    Private ReadOnly _startTray As New NumericUpDown()

    Public ReadOnly Property ItemValue As String
        Get
            Return _item.Text
        End Get
    End Property

    Public ReadOnly Property PlateNoValue As String
        Get
            Return _plate.Text
        End Get
    End Property

    Public ReadOnly Property DateTimeValue As String
        Get
            Return _dateTime.Text
        End Get
    End Property

    Public ReadOnly Property CapaValue As String
        Get
            Return _capa.Text
        End Get
    End Property

    Public ReadOnly Property DomeTypeValue As String
        Get
            Return _dome.Text
        End Get
    End Property

    Public ReadOnly Property Longtail83Value As String
        Get
            Return _longtail83.Text
        End Get
    End Property

    Public ReadOnly Property Longtail95Value As String
        Get
            Return _longtail95.Text
        End Get
    End Property

    Public ReadOnly Property CoatLotValue As String
        Get
            Return _coatLot.Text
        End Get
    End Property

    Public ReadOnly Property OperatorValue As String
        Get
            Return _operator.Text.Trim()
        End Get
    End Property

    Public ReadOnly Property StartTrayPositionValue As Integer
        Get
            Return CInt(_startTray.Value)
        End Get
    End Property

    Public Sub New(sheet As SheetData)
        Text = "Edit Report Header"
        StartPosition = FormStartPosition.CenterParent
        FormBorderStyle = FormBorderStyle.FixedDialog
        ClientSize = New Size(460, 405)
        Dim layout As New TableLayoutPanel With {.Dock = DockStyle.Fill, .Padding = New Padding(16), .ColumnCount = 2, .RowCount = 11}
        layout.ColumnStyles.Add(New ColumnStyle(SizeType.Absolute, 140))
        layout.ColumnStyles.Add(New ColumnStyle(SizeType.Percent, 100))
        Controls.Add(layout)
        AddField(layout, "ITEM", _item, sheet.Item, 0)
        AddField(layout, "PLATE No.", _plate, sheet.PlateNo, 1)
        AddField(layout, "DATETIME", _dateTime, sheet.DateTimeStamp, 2)
        AddField(layout, "CAPA.", _capa, sheet.Capa, 3)
        AddField(layout, "DOME Type", _dome, sheet.DomeType, 4)
        AddField(layout, "Longtail 83", _longtail83, sheet.Longtail83, 5)
        AddField(layout, "Longtail 95", _longtail95, sheet.Longtail95, 6)
        AddField(layout, "Coat Lot No.", _coatLot, sheet.CoatLotNo, 7)
        AddField(layout, "Operator", _operator, sheet.OperatorName, 8)
        AddNumber(layout, "Start T-*", _startTray, sheet.StartTrayPosition, 9)
        Dim save = New Button With {.Text = "Save", .DialogResult = DialogResult.OK}
        AddHandler save.Click, AddressOf Submit
        layout.Controls.Add(save, 1, 10)
        AcceptButton = save
    End Sub

    Private Shared Sub AddField(layout As TableLayoutPanel, label As String, entry As TextBox, value As String, row As Integer)
        layout.Controls.Add(New Label With {.Text = label, .AutoSize = True}, 0, row)
        entry.Text = value
        entry.Dock = DockStyle.Fill
        layout.Controls.Add(entry, 1, row)
    End Sub

    Private Shared Sub AddNumber(layout As TableLayoutPanel, label As String, entry As NumericUpDown, value As Integer, row As Integer)
        layout.Controls.Add(New Label With {.Text = label, .AutoSize = True}, 0, row)
        entry.Minimum = 1
        entry.Maximum = 999
        entry.Value = Math.Clamp(value, 1, 999)
        entry.Dock = DockStyle.Fill
        layout.Controls.Add(entry, 1, row)
    End Sub

    Private Sub Submit(sender As Object, eventArgs As EventArgs)
        If String.IsNullOrWhiteSpace(_operator.Text) Then
            MessageBox.Show(Me, "Enter Operator before saving.", "Missing Operator", MessageBoxButtons.OK, MessageBoxIcon.Warning)
            DialogResult = DialogResult.None
        End If
    End Sub
End Class

Public NotInheritable Class StartupSetupDialog
    Inherits Form

    Private ReadOnly _operator As New TextBox()
    Private ReadOnly _startTray As New NumericUpDown()

    Public ReadOnly Property OperatorNameValue As String
        Get
            Return _operator.Text.Trim()
        End Get
    End Property

    Public ReadOnly Property StartTrayPositionValue As Integer
        Get
            Return CInt(_startTray.Value)
        End Get
    End Property

    Public Sub New()
        Text = "Report setup"
        StartPosition = FormStartPosition.CenterParent
        FormBorderStyle = FormBorderStyle.FixedDialog
        MaximizeBox = False
        MinimizeBox = False
        ClientSize = New Size(390, 170)

        Dim layout As New TableLayoutPanel With {.Dock = DockStyle.Fill, .Padding = New Padding(16), .ColumnCount = 2, .RowCount = 3}
        layout.ColumnStyles.Add(New ColumnStyle(SizeType.Absolute, 130))
        layout.ColumnStyles.Add(New ColumnStyle(SizeType.Percent, 100))
        Controls.Add(layout)

        layout.Controls.Add(New Label With {.Text = "Operator", .AutoSize = True}, 0, 0)
        _operator.Dock = DockStyle.Fill
        layout.Controls.Add(_operator, 1, 0)

        layout.Controls.Add(New Label With {.Text = "Start T-*", .AutoSize = True}, 0, 1)
        _startTray.Minimum = 1
        _startTray.Maximum = 999
        _startTray.Value = 1
        _startTray.Dock = DockStyle.Fill
        layout.Controls.Add(_startTray, 1, 1)

        Dim buttons As New FlowLayoutPanel With {.Dock = DockStyle.Fill, .FlowDirection = FlowDirection.RightToLeft}
        Dim ok = New Button With {.Text = "Start", .DialogResult = DialogResult.OK}
        AddHandler ok.Click, AddressOf Submit
        buttons.Controls.Add(ok)
        buttons.Controls.Add(New Button With {.Text = "Cancel", .DialogResult = DialogResult.Cancel})
        layout.Controls.Add(buttons, 0, 2)
        layout.SetColumnSpan(buttons, 2)
        AcceptButton = ok
        CancelButton = buttons.Controls.OfType(Of Button)().Last()
    End Sub

    Private Sub Submit(sender As Object, eventArgs As EventArgs)
        If String.IsNullOrWhiteSpace(_operator.Text) Then
            MessageBox.Show(Me, "Enter Operator before continuing.", "Missing Operator", MessageBoxButtons.OK, MessageBoxIcon.Warning)
            DialogResult = DialogResult.None
        End If
    End Sub
End Class

Public NotInheritable Class StartTrayDialog
    Inherits Form

    Private ReadOnly _startTray As New NumericUpDown()

    Public ReadOnly Property StartTrayPositionValue As Integer
        Get
            Return CInt(_startTray.Value)
        End Get
    End Property

    Public Sub New(currentStartTray As Integer)
        Text = "Adjust data start T"
        StartPosition = FormStartPosition.CenterParent
        FormBorderStyle = FormBorderStyle.FixedDialog
        MaximizeBox = False
        MinimizeBox = False
        ClientSize = New Size(420, 155)

        Dim layout As New TableLayoutPanel With {.Dock = DockStyle.Fill, .Padding = New Padding(16), .ColumnCount = 2, .RowCount = 3}
        layout.ColumnStyles.Add(New ColumnStyle(SizeType.Absolute, 140))
        layout.ColumnStyles.Add(New ColumnStyle(SizeType.Percent, 100))
        Controls.Add(layout)

        layout.Controls.Add(New Label With {
            .Text = "Data starts at T-*",
            .AutoSize = True
        }, 0, 0)
        _startTray.Minimum = 1
        _startTray.Maximum = 999
        _startTray.Value = Math.Clamp(currentStartTray, 1, 999)
        _startTray.Dock = DockStyle.Fill
        layout.Controls.Add(_startTray, 1, 0)

        Dim note As New Label With {
            .Text = "This moves imported data only. Printed T-1..T-22 positions stay fixed.",
            .AutoSize = True,
            .ForeColor = Color.DarkSlateGray
        }
        layout.Controls.Add(note, 0, 1)
        layout.SetColumnSpan(note, 2)

        Dim buttons As New FlowLayoutPanel With {.Dock = DockStyle.Fill, .FlowDirection = FlowDirection.RightToLeft}
        buttons.Controls.Add(New Button With {.Text = "Apply", .DialogResult = DialogResult.OK})
        buttons.Controls.Add(New Button With {.Text = "Cancel", .DialogResult = DialogResult.Cancel})
        layout.Controls.Add(buttons, 0, 2)
        layout.SetColumnSpan(buttons, 2)
        AcceptButton = buttons.Controls.OfType(Of Button)().First()
        CancelButton = buttons.Controls.OfType(Of Button)().Last()
    End Sub
End Class
