Option Strict On
Option Explicit On

Imports AutoGenerateDiameter.Core
Imports System.Globalization
Imports System.Text

Public Partial Class Form1
    Private ReadOnly _preview As New ReportPreviewControl()
    Private ReadOnly _status As New ToolStripStatusLabel("Ready")
    Private ReadOnly _compareStatus As New ToolStripStatusLabel("Manual Compare: NOT RUN")
    Private ReadOnly _pageStatus As New ToolStripStatusLabel()
    Private ReadOnly _previous As New Button()
    Private ReadOnly _next As New Button()
    Private ReadOnly _resumeCompare As New Button()
    Private _report As ImportedReport = EmptyReportFactory.Create()
    Private _manualCompareResult As CompareResult
    Private _pageIndex As Integer
    Private _operatorName As String = ""
    Private _startTrayPosition As Integer = 1

    Public Sub New()
        InitializeComponent()
        BuildUi()
        AddHandler Shown, AddressOf PromptStartupSetup
        ShowPage()
    End Sub

    Private Sub BuildUi()
        Dim toolbar = New FlowLayoutPanel With {
            .Dock = DockStyle.Top,
            .Height = 78,
            .Padding = New Padding(16, 12, 16, 8),
            .BackColor = Color.White,
            .WrapContents = False
        }
        toolbar.Controls.Add(New Label With {
            .Text = "AUTO GENERATE DIAMETER",
            .AutoSize = False,
            .Width = 390,
            .Height = 44,
            .Font = New Font("Segoe UI", 18, FontStyle.Bold),
            .TextAlign = ContentAlignment.MiddleLeft
        })
        toolbar.Controls.Add(ActionButton("Load Database", AddressOf LoadDatabase))
        toolbar.Controls.Add(ActionButton("Import XLSX", AddressOf ImportXlsx))
        toolbar.Controls.Add(ActionButton("Import Manual Image", AddressOf ImportManualImage))
        toolbar.Controls.Add(ActionButton("Edit Header", AddressOf EditHeader))
        toolbar.Controls.Add(ActionButton("Adjust Start T", AddressOf AdjustStartTray))
        toolbar.Controls.Add(ActionButton("Export CSV", AddressOf ExportCsv))
        toolbar.Controls.Add(ActionButton("Compare Manual", AddressOf CompareManual))
        _resumeCompare.Text = "Resume Compare"
        ConfigureButton(_resumeCompare)
        _resumeCompare.Enabled = False
        AddHandler _resumeCompare.Click, AddressOf ResumeManualCompare
        toolbar.Controls.Add(_resumeCompare)

        _previous.Text = "< Previous"
        ConfigureButton(_previous)
        AddHandler _previous.Click, Sub() ChangePage(-1)
        toolbar.Controls.Add(_previous)

        _next.Text = "Next >"
        ConfigureButton(_next)
        AddHandler _next.Click, Sub() ChangePage(1)
        toolbar.Controls.Add(_next)

        Dim viewport = New Panel With {
            .Dock = DockStyle.Fill,
            .AutoScroll = True,
            .BackColor = Color.FromArgb(212, 215, 220),
            .Padding = New Padding(12)
        }
        viewport.Controls.Add(_preview)

        Dim statusBar = New StatusStrip With {.BackColor = Color.FromArgb(23, 32, 51)}
        _status.ForeColor = Color.White
        _status.Font = New Font("Segoe UI", 9, FontStyle.Bold)
        _pageStatus.ForeColor = Color.Gainsboro
        _pageStatus.Spring = True
        _pageStatus.TextAlign = ContentAlignment.MiddleRight
        statusBar.Items.Add(_status)
        statusBar.Items.Add(New ToolStripStatusLabel("Wheel: Zoom | Left drag: Pan") With {.ForeColor = Color.Gainsboro})
        _compareStatus.ForeColor = Color.Gold
        _compareStatus.Font = New Font("Segoe UI", 9, FontStyle.Bold)
        statusBar.Items.Add(_compareStatus)
        statusBar.Items.Add(_pageStatus)

        Controls.Add(viewport)
        Controls.Add(toolbar)
        Controls.Add(statusBar)
    End Sub

    Private Sub PromptStartupSetup(sender As Object, eventArgs As EventArgs)
        RemoveHandler Shown, AddressOf PromptStartupSetup
        Using dialog As New StartupSetupDialog()
            If dialog.ShowDialog(Me) <> DialogResult.OK Then
                Close()
                Return
            End If
            _operatorName = dialog.OperatorNameValue
            _startTrayPosition = dialog.StartTrayPositionValue
            ApplyReportDefaults()
            ShowPage("Operator ready")
        End Using
    End Sub

    Private Sub ImportManualImage(sender As Object, eventArgs As EventArgs)
        Using fileDialog As New OpenFileDialog With {
            .Title = "Import data from manual sheet image",
            .Filter = "Image files|*.png;*.jpg;*.jpeg;*.bmp;*.tif;*.tiff"
        }
            If fileDialog.ShowDialog(Me) <> DialogResult.OK Then Return
            Try
                _status.Text = $"Reading {IO.Path.GetFileName(fileDialog.FileName)}..."
                Application.DoEvents()
                Dim service As New ManualImageImportService()
                Dim result = service.ReadImage(fileDialog.FileName)
                Using review As New ManualImageImportDialog(result)
                    If review.ShowDialog(Me) <> DialogResult.OK Then
                        _status.Text = "Manual image import cancelled"
                        Return
                    End If
                    _report = service.BuildReport(
                        result.Rows,
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        0,
                        0
                    )
                End Using
                ApplyReportDefaults(repositionData:=False)
                ResetManualCompare()
                _pageIndex = 0
                ShowPage("Manual image imported")
                MessageBox.Show(
                    Me,
                    $"Imported {_report.MeasurementCount} rows from manual image. Review OCR values before use.",
                    "Import Manual Image complete",
                    MessageBoxButtons.OK,
                    MessageBoxIcon.Information
                )
            Catch ex As Exception
                _status.Text = "Manual image import failed"
                MessageBox.Show(Me, ex.Message, "Import Manual Image failed", MessageBoxButtons.OK, MessageBoxIcon.Error)
            End Try
        End Using
    End Sub

    Private Shared Function ActionButton(text As String, handler As EventHandler) As Button
        Dim button As New Button With {.Text = text}
        ConfigureButton(button)
        AddHandler button.Click, handler
        Return button
    End Function

    Private Shared Sub ConfigureButton(button As Button)
        button.AutoSize = True
        button.Height = 38
        button.Padding = New Padding(10, 4, 10, 4)
        button.Margin = New Padding(6, 8, 0, 0)
        button.FlatStyle = FlatStyle.Flat
        button.FlatAppearance.BorderSize = 0
        button.BackColor = Color.FromArgb(242, 244, 247)
        button.Font = New Font("Segoe UI", 10)
    End Sub

    Private Sub ShowPage(Optional activity As String = "Ready")
        If _report.Sheets.Count = 0 Then Return
        _pageIndex = Math.Clamp(_pageIndex, 0, _report.Sheets.Count - 1)
        _preview.Sheet = _report.Sheets(_pageIndex)
        _previous.Enabled = _pageIndex > 0
        _next.Enabled = _pageIndex < _report.Sheets.Count - 1
        _status.Text = activity
        _pageStatus.Text = $"Page {_pageIndex + 1}/{_report.Sheets.Count} | Records: {_report.Sheets(_pageIndex).Measurements.Count}"
    End Sub

    Private Sub ChangePage(offset As Integer)
        _pageIndex += offset
        ResetManualCompare()
        ShowPage()
    End Sub

    Private Sub ImportXlsx(sender As Object, eventArgs As EventArgs)
        Using dialog As New OpenFileDialog With {
            .Title = "Import diameter data from XLSX",
            .Filter = "Excel workbook (*.xlsx)|*.xlsx"
        }
            If dialog.ShowDialog(Me) <> DialogResult.OK Then Return
            Try
                _status.Text = $"Importing {IO.Path.GetFileName(dialog.FileName)}..."
                Application.DoEvents()
                _report = New XlsxReportImporter().Import(dialog.FileName)
                ApplyReportDefaults()
                ResetManualCompare()
                _pageIndex = 0
                ShowPage("XLSX imported")
                MessageBox.Show(
                    Me,
                    $"Imported {_report.MeasurementCount} R/L pairs into {_report.Sheets.Count} page(s).",
                    "Import XLSX complete",
                    MessageBoxButtons.OK,
                    MessageBoxIcon.Information
                )
            Catch ex As Exception
                _status.Text = "Import failed"
                MessageBox.Show(Me, ex.Message, "Import XLSX failed", MessageBoxButtons.OK, MessageBoxIcon.Error)
            End Try
        End Using
    End Sub

    Private Async Sub LoadDatabase(sender As Object, eventArgs As EventArgs)
        Using dialog As New DatabaseLoadDialog()
            If dialog.ShowDialog(Me) <> DialogResult.OK Then Return
            Try
                _status.Text = $"Loading CLN {dialog.CoatLotNumber} from MySQL..."
                Application.DoEvents()
                _report = Await New MySqlReportLoader().LoadAsync(dialog.Settings, dialog.ProductionPlaceCode, dialog.CoatLotNumber)
                ApplyReportDefaults()
                ResetManualCompare()
                _pageIndex = 0
                ShowPage("Database loaded")
                MessageBox.Show(
                    Me,
                    $"Loaded {_report.MeasurementCount} R/L pairs into {_report.Sheets.Count} page(s).",
                    "Load Database complete",
                    MessageBoxButtons.OK,
                    MessageBoxIcon.Information
                )
            Catch ex As Exception
                _status.Text = "Database load failed"
                MessageBox.Show(Me, ex.Message, "Load Database failed", MessageBoxButtons.OK, MessageBoxIcon.Error)
            End Try
        End Using
    End Sub

    Private Sub EditHeader(sender As Object, eventArgs As EventArgs)
        Using dialog As New HeaderEditDialog(_report.Sheets(_pageIndex))
            If dialog.ShowDialog(Me) <> DialogResult.OK Then Return
            RepositionReportData(dialog.StartTrayPositionValue)
            For Each sheet In _report.Sheets
                sheet.Item = dialog.ItemValue
                sheet.PlateNo = dialog.PlateNoValue
                sheet.DomeType = dialog.DomeTypeValue
                sheet.Capa = dialog.CapaValue
                sheet.DateTimeStamp = dialog.DateTimeValue
                sheet.Longtail83 = dialog.Longtail83Value
                sheet.Longtail95 = dialog.Longtail95Value
                sheet.CoatLotNo = dialog.CoatLotValue
                sheet.OperatorName = dialog.OperatorValue
                sheet.StartTrayPosition = dialog.StartTrayPositionValue
            Next
            _operatorName = dialog.OperatorValue
            _startTrayPosition = dialog.StartTrayPositionValue
            ResetManualCompare()
            ShowPage("Header updated")
        End Using
    End Sub

    Private Sub AdjustStartTray(sender As Object, eventArgs As EventArgs)
        Using dialog As New StartTrayDialog(_startTrayPosition)
            If dialog.ShowDialog(Me) <> DialogResult.OK Then Return
            RepositionReportData(dialog.StartTrayPositionValue)
            For Each sheet In _report.Sheets
                sheet.StartTrayPosition = dialog.StartTrayPositionValue
            Next
            _startTrayPosition = dialog.StartTrayPositionValue
            ResetManualCompare()
            ShowPage($"Data starts at T-{_startTrayPosition}")
        End Using
    End Sub

    Private Sub ExportCsv(sender As Object, eventArgs As EventArgs)
        If _report.Sheets.Count = 0 OrElse _report.MeasurementCount = 0 Then
            MessageBox.Show(Me, "No report data to export.", "Export CSV", MessageBoxButtons.OK, MessageBoxIcon.Warning)
            Return
        End If
        Using dialog As New SaveFileDialog With {
            .Title = "Export report data to CSV",
            .Filter = "CSV file (*.csv)|*.csv",
            .FileName = $"AutoGenerateDiameter_{Date.Now:yyyyMMdd_HHmmss}.csv"
        }
            If dialog.ShowDialog(Me) <> DialogResult.OK Then Return
            Try
                IO.File.WriteAllText(dialog.FileName, BuildCsv(), New UTF8Encoding(True))
                _status.Text = "CSV exported"
                MessageBox.Show(Me, "CSV export complete.", "Export CSV", MessageBoxButtons.OK, MessageBoxIcon.Information)
            Catch ex As Exception
                _status.Text = "CSV export failed"
                MessageBox.Show(Me, ex.Message, "Export CSV failed", MessageBoxButtons.OK, MessageBoxIcon.Error)
            End Try
        End Using
    End Sub

    Private Function BuildCsv() As String
        Dim lines As New List(Of String) From {
            String.Join(",", {"Page", "TLabel", "TPosition", "Row", "DipLot", "Side", "Diameter", "TrayNumber", "Display", "Item", "PlateNo", "DateTime", "Capa", "DomeType", "Longtail83", "Longtail95", "CoatLotNo", "Operator"}.Select(AddressOf Csv))
        }
        For Each sheet In _report.Sheets
            For Each measurement In sheet.Measurements.OrderBy(Function(item) item.TrayPosition).ThenBy(Function(item) item.RowNumber)
                AddCsvSide(lines, sheet, measurement, "R", measurement.RPresent, measurement.RDash, measurement.RDiameter)
                AddCsvSide(lines, sheet, measurement, "L", measurement.LPresent, measurement.LDash, measurement.LDiameter)
            Next
        Next
        Return String.Join(Environment.NewLine, lines) & Environment.NewLine
    End Function

    Private Shared Sub AddCsvSide(lines As List(Of String), sheet As SheetData, measurement As Measurement, side As String, present As Boolean, dash As Boolean, diameter As Double)
        If Not present AndAlso Not dash Then Return
        Dim trayLabel = ((sheet.PageNumber - 1) * 22) + measurement.TrayPosition
        Dim diameterText = If(dash, "", Math.Round(diameter).ToString(CultureInfo.InvariantCulture))
        Dim display = If(dash, "-", diameterText)
        Dim values = {
            sheet.PageNumber.ToString(CultureInfo.InvariantCulture),
            $"T-{trayLabel}",
            measurement.TrayPosition.ToString(CultureInfo.InvariantCulture),
            measurement.RowNumber.ToString(CultureInfo.InvariantCulture),
            measurement.LotNumber,
            side,
            diameterText,
            measurement.TrayNumber,
            display,
            sheet.Item,
            sheet.PlateNo,
            sheet.DateTimeStamp,
            sheet.Capa,
            sheet.DomeType,
            sheet.Longtail83,
            sheet.Longtail95,
            sheet.CoatLotNo,
            sheet.OperatorName
        }
        lines.Add(String.Join(",", values.Select(AddressOf Csv)))
    End Sub

    Private Shared Function Csv(value As String) As String
        Dim text = If(value, "")
        Return $"""{text.Replace("""", """""")}"""
    End Function

    Private Sub ApplyReportDefaults(Optional repositionData As Boolean = True)
        If repositionData Then RepositionReportData(_startTrayPosition)
        For Each sheet In _report.Sheets
            sheet.Item = ""
            sheet.PlateNo = ""
            sheet.DateTimeStamp = ""
            sheet.DomeType = ""
            sheet.Capa = ""
            sheet.Longtail83 = ""
            sheet.Longtail95 = ""
            sheet.CoatLotNo = ""
            sheet.OperatorName = _operatorName
            sheet.StartTrayPosition = _startTrayPosition
        Next
    End Sub

    Private Sub RepositionReportData(newStartTrayPosition As Integer)
        If _report.Sheets.Count = 0 OrElse _report.MeasurementCount = 0 Then Return

        Dim oldStartTrayPosition = Math.Max(1, _report.Sheets(0).StartTrayPosition)
        Dim allMeasurements = _report.Sheets.
            SelectMany(Function(sheet) sheet.Measurements.Select(
                Function(measurement) New With {
                    .LogicalPosition = ((sheet.PageNumber - 1) * 22) + measurement.TrayPosition - oldStartTrayPosition + 1,
                    .Measurement = measurement
                }
            )).
            Where(Function(item) item.LogicalPosition >= 1).
            ToList()

        If allMeasurements.Count = 0 Then Return

        Dim maxDisplayPosition = allMeasurements.Max(Function(item) item.LogicalPosition + newStartTrayPosition - 1)
        Dim totalPages = Math.Max(1, CInt(Math.Ceiling(maxDisplayPosition / 22.0)))
        Dim template = _report.Sheets(0)
        Dim newSheets As New List(Of SheetData)

        For pageNumber = 1 To totalPages
            newSheets.Add(New SheetData With {
                .PageNumber = pageNumber,
                .TotalPages = totalPages,
                .Item = template.Item,
                .PlateNo = template.PlateNo,
                .DateTimeStamp = template.DateTimeStamp,
                .DomeType = template.DomeType,
                .Capa = template.Capa,
                .Longtail83 = template.Longtail83,
                .Longtail95 = template.Longtail95,
                .CoatLotNo = template.CoatLotNo,
                .OperatorName = template.OperatorName,
                .StartTrayPosition = newStartTrayPosition
            })
        Next

        For Each item In allMeasurements
            Dim displayPosition = item.LogicalPosition + newStartTrayPosition - 1
            Dim pageIndex = (displayPosition - 1) \ 22
            Dim trayPosition = ((displayPosition - 1) Mod 22) + 1
            newSheets(pageIndex).Measurements.Add(CloneMeasurement(item.Measurement, trayPosition))
        Next

        For Each sheet In newSheets
            sheet.Measurements = sheet.Measurements.
                OrderBy(Function(item) item.TrayPosition).
                ThenBy(Function(item) item.RowNumber).
                ToList()
        Next
        _report.Sheets = newSheets
        _pageIndex = Math.Clamp(_pageIndex, 0, _report.Sheets.Count - 1)
    End Sub

    Private Shared Function CloneMeasurement(source As Measurement, trayPosition As Integer) As Measurement
        Return New Measurement With {
            .TrayPosition = trayPosition,
            .RowNumber = source.RowNumber,
            .LotNumber = source.LotNumber,
            .RDiameter = source.RDiameter,
            .LDiameter = source.LDiameter,
            .TrayNumber = source.TrayNumber,
            .RPresent = source.RPresent,
            .LPresent = source.LPresent,
            .RDash = source.RDash,
            .LDash = source.LDash
        }
    End Function

    Private Sub CompareManual(sender As Object, eventArgs As EventArgs)
        Using dialog As New OpenFileDialog With {
            .Title = "Compare manual sheet image",
            .Filter = "Image files|*.png;*.jpg;*.jpeg;*.bmp;*.tif;*.tiff"
        }
            If dialog.ShowDialog(Me) <> DialogResult.OK Then Return
            Dim preparedImagePath As String = ""
            Dim ocrImagePath As String = ""
            Try
                Using alignmentDialog As New ManualImageAlignmentDialog(dialog.FileName)
                    If alignmentDialog.ShowDialog(Me) <> DialogResult.OK Then Return
                    preparedImagePath = alignmentDialog.ResultImagePath
                    _status.Text = $"Preprocessing {IO.Path.GetFileName(dialog.FileName)}..."
                    Application.DoEvents()
                    ocrImagePath = ImagePreprocessor.Preprocess(preparedImagePath)
                    _status.Text = $"Comparing {IO.Path.GetFileName(dialog.FileName)}..."
                    Application.DoEvents()

                    Dim service As New ManualCompareService()
                    Dim result As CompareResult
                    ' Cell-level OCR only makes sense when the table geometry is reliable, i.e. the
                    ' user perspective-aligned or cropped the frame (temp file prefixed "-aligned-").
                    ' For an unaligned original photo, fall back to whole-image OCR.
                    If IsAlignedImage(preparedImagePath) Then
                        Dim cropSource = preparedImagePath
                        result = service.CompareImageByCell(
                            ocrImagePath,
                            _report.Sheets(_pageIndex),
                            Function(region) ImagePreprocessor.ExtractCell(cropSource, region))
                    Else
                        result = service.CompareImage(ocrImagePath, _report.Sheets(_pageIndex))
                    End If
                    result.ImagePath = preparedImagePath
                    DeleteTemporaryImage(ocrImagePath)
                    ocrImagePath = ""
                    ResetManualCompare()
                    _manualCompareResult = result
                    OpenManualCompareResult()
                End Using
            Catch ex As Exception
                DeleteTemporaryImage(ocrImagePath)
                DeleteTemporaryImage(preparedImagePath)
                _status.Text = "Manual comparison failed"
                MessageBox.Show(Me, ex.Message, "Manual comparison failed", MessageBoxButtons.OK, MessageBoxIcon.Error)
            End Try
        End Using
    End Sub

    Private Sub ResetManualCompare()
        DeleteTemporaryCompareImage()
        _manualCompareResult = Nothing
        UpdateManualCompareBadge()
    End Sub

    Private Sub DeleteTemporaryCompareImage()
        If _manualCompareResult Is Nothing OrElse String.IsNullOrWhiteSpace(_manualCompareResult.ImagePath) Then Return
        DeleteTemporaryImage(_manualCompareResult.ImagePath)
    End Sub

    Private Shared Function IsAlignedImage(path As String) As Boolean
        If String.IsNullOrWhiteSpace(path) Then Return False
        Return IO.Path.GetFileName(path).StartsWith("AutoGenerateDiameter-aligned-", StringComparison.OrdinalIgnoreCase)
    End Function

    Private Shared Sub DeleteTemporaryImage(path As String)
        If String.IsNullOrWhiteSpace(path) Then Return
        Dim fileName = IO.Path.GetFileName(path)
        If Not (fileName.StartsWith("AutoGenerateDiameter-aligned-", StringComparison.OrdinalIgnoreCase) OrElse
                fileName.StartsWith("AutoGenerateDiameter-ocr-", StringComparison.OrdinalIgnoreCase)) Then Return
        Try
            If IO.File.Exists(path) Then IO.File.Delete(path)
        Catch
            ' A temporary preview file can remain if another control still has it open.
        End Try
    End Sub

    Private Sub ResumeManualCompare(sender As Object, eventArgs As EventArgs)
        If _manualCompareResult Is Nothing Then Return
        OpenManualCompareResult()
    End Sub

    Private Sub OpenManualCompareResult()
        Using resultDialog As New ManualCompareDialog(_manualCompareResult)
            resultDialog.ShowDialog(Me)
        End Using
        UpdateManualCompareBadge()
        _status.Text = If(_manualCompareResult.Verified, "Manual comparison verified", "Manual comparison saved in session with pending items")
    End Sub

    Private Sub UpdateManualCompareBadge()
        _resumeCompare.Enabled = _manualCompareResult IsNot Nothing
        If _manualCompareResult Is Nothing Then
            _compareStatus.Text = "Manual Compare: NOT RUN"
            _compareStatus.ForeColor = Color.Gold
        ElseIf _manualCompareResult.Verified Then
            _compareStatus.Text = $"Manual Compare: VERIFIED | OCR Match: {_manualCompareResult.FoundCount} | Manual Confirmed: {_manualCompareResult.ManuallyConfirmedCount}"
            _compareStatus.ForeColor = Color.LightGreen
        Else
            _compareStatus.Text = $"Manual Compare: REVIEW REQUIRED | Pending: {_manualCompareResult.PendingCount}"
            _compareStatus.ForeColor = Color.OrangeRed
        End If
    End Sub

    Private Function CanExportOrPrint() As Boolean
        Return True
    End Function
End Class
