Option Strict On
Option Explicit On

Imports AutoGenerateDiameter.Core
Imports System.Globalization
Imports System.Text

Public Partial Class Form1
    Private ReadOnly _preview As New ReportPreviewControl()
    Private ReadOnly _status As New ToolStripStatusLabel("Ready")
    Private ReadOnly _pageStatus As New ToolStripStatusLabel()
    Private ReadOnly _previous As New Button()
    Private ReadOnly _next As New Button()
    Private _report As ImportedReport = EmptyReportFactory.Create()
    Private _pageIndex As Integer
    Private _operatorName As String = ""
    Private _startTrayPosition As Integer = 1
    Private ReadOnly _editLog As New EditLogStore(EditLogPath())

    Public Sub New()
        InitializeComponent()
        BuildUi()
        AddHandler Shown, AddressOf PromptStartupSetup
        ShowPage()
    End Sub

    Private Sub BuildUi()
        Dim toolbar = New FlowLayoutPanel With {
            .Dock = DockStyle.Top,
            .Height = 78,
            .Padding = New Padding(16, 12, 16, 8),
            .BackColor = Color.White,
            .WrapContents = False
        }
        toolbar.Controls.Add(New Label With {
            .Text = "AUTO GENERATE DIAMETER",
            .AutoSize = False,
            .Width = 390,
            .Height = 44,
            .Font = New Font("Segoe UI", 18, FontStyle.Bold),
            .TextAlign = ContentAlignment.MiddleLeft
        })
        toolbar.Controls.Add(ActionButton("Load Database", AddressOf LoadDatabase))
        toolbar.Controls.Add(ActionButton("Import XLSX", AddressOf ImportXlsx))
        toolbar.Controls.Add(ActionButton("Edit Header", AddressOf EditHeader))
        toolbar.Controls.Add(ActionButton("Adjust Start T", AddressOf AdjustStartTray))
        toolbar.Controls.Add(ActionButton("Export CSV", AddressOf ExportCsv))
        toolbar.Controls.Add(ActionButton("View Edit Log", AddressOf OpenEditLog))

        _previous.Text = "< Previous"
        ConfigureButton(_previous)
        AddHandler _previous.Click, Sub() ChangePage(-1)
        toolbar.Controls.Add(_previous)

        _next.Text = "Next >"
        ConfigureButton(_next)
        AddHandler _next.Click, Sub() ChangePage(1)
        toolbar.Controls.Add(_next)

        Dim viewport = New Panel With {
            .Dock = DockStyle.Fill,
            .AutoScroll = True,
            .BackColor = Color.FromArgb(212, 215, 220),
            .Padding = New Padding(12)
        }
        viewport.Controls.Add(_preview)
        AddHandler _preview.CellDoubleClicked, AddressOf EditReportCell
        AddHandler _preview.TrayHeaderDoubleClicked, AddressOf EditTrayLot
        AddHandler _preview.HeaderDoubleClicked, Sub() EditHeader(Me, EventArgs.Empty)
        AddHandler _preview.OperatorDoubleClicked, AddressOf EditOperator

        Dim statusBar = New StatusStrip With {.BackColor = Color.FromArgb(23, 32, 51)}
        _status.ForeColor = Color.White
        _status.Font = New Font("Segoe UI", 9, FontStyle.Bold)
        _pageStatus.ForeColor = Color.Gainsboro
        _pageStatus.Spring = True
        _pageStatus.TextAlign = ContentAlignment.MiddleRight
        statusBar.Items.Add(_status)
        statusBar.Items.Add(New ToolStripStatusLabel("Wheel: Zoom | Left drag: Pan | Double-click: cell / T-* lot / header / operator to edit") With {.ForeColor = Color.Gainsboro})
        statusBar.Items.Add(_pageStatus)

        Controls.Add(viewport)
        Controls.Add(toolbar)
        Controls.Add(statusBar)
    End Sub

    Private Sub PromptStartupSetup(sender As Object, eventArgs As EventArgs)
        RemoveHandler Shown, AddressOf PromptStartupSetup
        Using dialog As New StartupSetupDialog()
            If dialog.ShowDialog(Me) <> DialogResult.OK Then
                Close()
                Return
            End If
            _operatorName = dialog.OperatorNameValue
            _startTrayPosition = dialog.StartTrayPositionValue
            ApplyReportDefaults()
            ShowPage("Operator ready")
        End Using
    End Sub

    Private Shared Function ActionButton(text As String, handler As EventHandler) As Button
        Dim button As New Button With {.Text = text}
        ConfigureButton(button)
        AddHandler button.Click, handler
        Return button
    End Function

    Private Shared Sub ConfigureButton(button As Button)
        button.AutoSize = True
        button.Height = 38
        button.Padding = New Padding(10, 4, 10, 4)
        button.Margin = New Padding(6, 8, 0, 0)
        button.FlatStyle = FlatStyle.Flat
        button.FlatAppearance.BorderSize = 0
        button.BackColor = Color.FromArgb(242, 244, 247)
        button.Font = New Font("Segoe UI", 10)
    End Sub

    Private Sub ShowPage(Optional activity As String = "Ready")
        If _report.Sheets.Count = 0 Then Return
        _pageIndex = Math.Clamp(_pageIndex, 0, _report.Sheets.Count - 1)
        _preview.Sheet = _report.Sheets(_pageIndex)
        _previous.Enabled = _pageIndex > 0
        _next.Enabled = _pageIndex < _report.Sheets.Count - 1
        _status.Text = activity
        _pageStatus.Text = $"Page {_pageIndex + 1}/{_report.Sheets.Count} | Records: {_report.Sheets(_pageIndex).Measurements.Count}"
    End Sub

    Private Sub ChangePage(offset As Integer)
        _pageIndex += offset
        ShowPage()
    End Sub

    Private Sub ImportXlsx(sender As Object, eventArgs As EventArgs)
        Using dialog As New OpenFileDialog With {
            .Title = "Import diameter data from XLSX",
            .Filter = "Excel workbook (*.xlsx)|*.xlsx"
        }
            If dialog.ShowDialog(Me) <> DialogResult.OK Then Return
            Try
                _status.Text = $"Importing {IO.Path.GetFileName(dialog.FileName)}..."
                Application.DoEvents()
                _report = New XlsxReportImporter().Import(dialog.FileName)
                ApplyReportDefaults()
                _pageIndex = 0
                ShowPage("XLSX imported")
                MessageBox.Show(
                    Me,
                    $"Imported {_report.MeasurementCount} R/L pairs into {_report.Sheets.Count} page(s).",
                    "Import XLSX complete",
                    MessageBoxButtons.OK,
                    MessageBoxIcon.Information
                )
            Catch ex As Exception
                _status.Text = "Import failed"
                MessageBox.Show(Me, ex.Message, "Import XLSX failed", MessageBoxButtons.OK, MessageBoxIcon.Error)
            End Try
        End Using
    End Sub

    Private Async Sub LoadDatabase(sender As Object, eventArgs As EventArgs)
        Using dialog As New DatabaseLoadDialog()
            If dialog.ShowDialog(Me) <> DialogResult.OK Then Return
            Try
                _status.Text = $"Loading CLN {dialog.CoatLotNumber} from MySQL..."
                Application.DoEvents()
                _report = Await New MySqlReportLoader().LoadAsync(dialog.Settings, dialog.ProductionPlaceCode, dialog.CoatLotNumber)
                ApplyReportDefaults()
                _pageIndex = 0
                ShowPage("Database loaded")
                MessageBox.Show(
                    Me,
                    $"Loaded {_report.MeasurementCount} R/L pairs into {_report.Sheets.Count} page(s).",
                    "Load Database complete",
                    MessageBoxButtons.OK,
                    MessageBoxIcon.Information
                )
            Catch ex As Exception
                _status.Text = "Database load failed"
                MessageBox.Show(Me, ex.Message, "Load Database failed", MessageBoxButtons.OK, MessageBoxIcon.Error)
            End Try
        End Using
    End Sub

    Private Sub EditHeader(sender As Object, eventArgs As EventArgs)
        Using dialog As New HeaderEditDialog(_report.Sheets(_pageIndex))
            If dialog.ShowDialog(Me) <> DialogResult.OK Then Return
            LogHeaderEdit(_report.Sheets(_pageIndex), dialog)
            RepositionReportData(dialog.StartTrayPositionValue)
            For Each sheet In _report.Sheets
                sheet.Item = dialog.ItemValue
                sheet.PlateNo = dialog.PlateNoValue
                sheet.DomeType = dialog.DomeTypeValue
                sheet.Capa = dialog.CapaValue
                sheet.DateTimeStamp = dialog.DateTimeValue
                sheet.Longtail83 = dialog.Longtail83Value
                sheet.Longtail95 = dialog.Longtail95Value
                sheet.CoatLotNo = dialog.CoatLotValue
                sheet.OperatorName = dialog.OperatorValue
                sheet.StartTrayPosition = dialog.StartTrayPositionValue
            Next
            _operatorName = dialog.OperatorValue
            _startTrayPosition = dialog.StartTrayPositionValue
            ShowPage("Header updated")
        End Using
    End Sub

    Private Sub AdjustStartTray(sender As Object, eventArgs As EventArgs)
        Using dialog As New StartTrayDialog(_startTrayPosition)
            If dialog.ShowDialog(Me) <> DialogResult.OK Then Return
            RepositionReportData(dialog.StartTrayPositionValue)
            For Each sheet In _report.Sheets
                sheet.StartTrayPosition = dialog.StartTrayPositionValue
            Next
            _startTrayPosition = dialog.StartTrayPositionValue
            ShowPage($"Data starts at T-{_startTrayPosition}")
        End Using
    End Sub

    Private Sub ExportCsv(sender As Object, eventArgs As EventArgs)
        If _report.Sheets.Count = 0 OrElse _report.MeasurementCount = 0 Then
            MessageBox.Show(Me, "No report data to export.", "Export CSV", MessageBoxButtons.OK, MessageBoxIcon.Warning)
            Return
        End If
        Using dialog As New SaveFileDialog With {
            .Title = "Export report data to CSV",
            .Filter = "CSV file (*.csv)|*.csv",
            .FileName = $"AutoGenerateDiameter_{Date.Now:yyyyMMdd_HHmmss}.csv"
        }
            If dialog.ShowDialog(Me) <> DialogResult.OK Then Return
            Try
                IO.File.WriteAllText(dialog.FileName, BuildCsv(), New UTF8Encoding(True))
                _status.Text = "CSV exported"
                MessageBox.Show(Me, "CSV export complete.", "Export CSV", MessageBoxButtons.OK, MessageBoxIcon.Information)
            Catch ex As Exception
                _status.Text = "CSV export failed"
                MessageBox.Show(Me, ex.Message, "Export CSV failed", MessageBoxButtons.OK, MessageBoxIcon.Error)
            End Try
        End Using
    End Sub

    Private Sub EditReportCell(sender As Object, eventArgs As ReportCellEventArgs)
        If _report.Sheets.Count = 0 Then Return
        Dim sheet = _report.Sheets(_pageIndex)
        Dim measurement = sheet.Measurements.FirstOrDefault(
            Function(item) item.TrayPosition = eventArgs.Hit.TrayPosition AndAlso item.RowNumber = eventArgs.Hit.RowNumber
        )
        Dim before = SnapshotCell(measurement, eventArgs.Hit.Side)

        Using dialog As New CellEditDialog(eventArgs.Hit, measurement)
            If dialog.ShowDialog(Me) <> DialogResult.OK Then Return
            If measurement Is Nothing Then
                measurement = New Measurement With {
                    .TrayPosition = eventArgs.Hit.TrayPosition,
                    .RowNumber = eventArgs.Hit.RowNumber
                }
                sheet.Measurements.Add(measurement)
            End If

            measurement.LotNumber = dialog.LotNumberValue
            measurement.TrayNumber = dialog.TrayNumberValue
            ApplyCellEdit(measurement, eventArgs.Hit.Side, dialog.DisplayModeValue, dialog.DiameterValue)

            Dim after = SnapshotCell(measurement, eventArgs.Hit.Side)
            If IsEmptyMeasurement(measurement) Then sheet.Measurements.Remove(measurement)
            sheet.Measurements = sheet.Measurements.
                OrderBy(Function(item) item.TrayPosition).
                ThenBy(Function(item) item.RowNumber).
                ToList()

            LogCellEdit(eventArgs.Hit, before, after)
            ShowPage($"Edited T-{eventArgs.Hit.TrayLabel} Row {eventArgs.Hit.RowNumber} {eventArgs.Hit.Side}")
        End Using
    End Sub

    Private Sub EditTrayLot(sender As Object, eventArgs As ReportCellEventArgs)
        If _report.Sheets.Count = 0 Then Return
        Dim sheet = _report.Sheets(_pageIndex)
        Dim measurements = sheet.Measurements.
            Where(Function(item) item.TrayPosition = eventArgs.Hit.TrayPosition).
            ToList()

        If measurements.Count = 0 Then
            MessageBox.Show(
                Me,
                $"T-{eventArgs.Hit.TrayLabel} has no data yet, so there is no Dip Lot to edit.",
                "Edit Dip Lot",
                MessageBoxButtons.OK,
                MessageBoxIcon.Information
            )
            Return
        End If

        Dim before = measurements(0).LotNumber
        Using dialog As New TrayLotEditDialog(eventArgs.Hit.TrayLabel, before)
            If dialog.ShowDialog(Me) <> DialogResult.OK Then Return
            For Each measurement In measurements
                measurement.LotNumber = dialog.LotNumberValue
            Next
            Dim entries As New List(Of EditLogEntry)
            AddEntry(entries, $"T-{eventArgs.Hit.TrayLabel}", "Dip Lot", before, dialog.LotNumberValue)
            _editLog.Append(entries)
            ShowPage($"Updated Dip Lot for T-{eventArgs.Hit.TrayLabel}")
        End Using
    End Sub

    Private Sub EditOperator(sender As Object, eventArgs As EventArgs)
        If _report.Sheets.Count = 0 Then Return
        Using dialog As New OperatorEditDialog(_operatorName)
            If dialog.ShowDialog(Me) <> DialogResult.OK Then Return
            Dim entries As New List(Of EditLogEntry)
            AddEntry(entries, "Operator", "Operator", _operatorName, dialog.OperatorNameValue)
            _editLog.Append(entries)
            _operatorName = dialog.OperatorNameValue
            For Each sheet In _report.Sheets
                sheet.OperatorName = _operatorName
            Next
            ShowPage("Operator updated")
        End Using
    End Sub

    Private Shared Sub ApplyCellEdit(measurement As Measurement, side As String, displayMode As String, diameter As Double)
        Dim isValue = displayMode = "Value"
        Dim isDash = displayMode = "Dash (-)"
        If side = "R" Then
            measurement.RPresent = isValue
            measurement.RDash = isDash
            measurement.RDiameter = If(isValue, diameter, 0)
            Return
        End If
        measurement.LPresent = isValue
        measurement.LDash = isDash
        measurement.LDiameter = If(isValue, diameter, 0)
    End Sub

    Private Shared Function IsEmptyMeasurement(measurement As Measurement) As Boolean
        Return Not measurement.RPresent AndAlso
            Not measurement.LPresent AndAlso
            Not measurement.RDash AndAlso
            Not measurement.LDash AndAlso
            String.IsNullOrWhiteSpace(measurement.TrayNumber) AndAlso
            String.IsNullOrWhiteSpace(measurement.LotNumber)
    End Function

    Private Shared Function SnapshotCell(measurement As Measurement, side As String) As CellSnapshot
        If measurement Is Nothing Then Return New CellSnapshot()

        Dim present = If(side = "R", measurement.RPresent, measurement.LPresent)
        Dim dash = If(side = "R", measurement.RDash, measurement.LDash)
        Dim diameter = If(side = "R", measurement.RDiameter, measurement.LDiameter)
        Dim displayMode = If(dash, "Dash (-)", If(present, "Value", "Blank"))
        Dim diameterText = If(present, Math.Round(diameter).ToString(CultureInfo.InvariantCulture), "")
        Dim displayText = If(dash, "-", diameterText)

        Return New CellSnapshot With {
            .DisplayMode = displayMode,
            .DisplayText = displayText,
            .DiameterText = diameterText,
            .TrayNumber = measurement.TrayNumber,
            .LotNumber = measurement.LotNumber
        }
    End Function

    Private Sub LogCellEdit(hit As ReportCellHit, before As CellSnapshot, after As CellSnapshot)
        Dim target = $"T-{hit.TrayLabel} Row {hit.RowNumber} {hit.Side}"
        Dim entries As New List(Of EditLogEntry)
        AddEntry(entries, target, "Value", before.DisplayText, after.DisplayText)
        AddEntry(entries, target, "Tray Number", before.TrayNumber, after.TrayNumber)
        AddEntry(entries, target, "Dip Lot", before.LotNumber, after.LotNumber)
        _editLog.Append(entries)
    End Sub

    Private Sub LogHeaderEdit(sheet As SheetData, dialog As HeaderEditDialog)
        Dim entries As New List(Of EditLogEntry)
        AddEntry(entries, "Header", "ITEM", sheet.Item, dialog.ItemValue)
        AddEntry(entries, "Header", "PLATE No.", sheet.PlateNo, dialog.PlateNoValue)
        AddEntry(entries, "Header", "DATETIME", sheet.DateTimeStamp, dialog.DateTimeValue)
        AddEntry(entries, "Header", "CAPA.", sheet.Capa, dialog.CapaValue)
        AddEntry(entries, "Header", "DOME Type", sheet.DomeType, dialog.DomeTypeValue)
        AddEntry(entries, "Header", "Longtail 83", sheet.Longtail83, dialog.Longtail83Value)
        AddEntry(entries, "Header", "Longtail 95", sheet.Longtail95, dialog.Longtail95Value)
        AddEntry(entries, "Header", "Coat Lot No.", sheet.CoatLotNo, dialog.CoatLotValue)
        AddEntry(entries, "Header", "Operator", sheet.OperatorName, dialog.OperatorValue)
        AddEntry(entries, "Header", "Start T-*",
            sheet.StartTrayPosition.ToString(CultureInfo.InvariantCulture),
            dialog.StartTrayPositionValue.ToString(CultureInfo.InvariantCulture))
        _editLog.Append(entries)
    End Sub

    Private Sub AddEntry(entries As List(Of EditLogEntry), target As String, field As String, oldValue As String, newValue As String)
        Dim previous = If(oldValue, "")
        Dim current = If(newValue, "")
        If String.Equals(previous, current, StringComparison.Ordinal) Then Return
        entries.Add(New EditLogEntry With {
            .Timestamp = Date.Now,
            .OperatorName = _operatorName,
            .Target = target,
            .Field = field,
            .OldValue = previous,
            .NewValue = current
        })
    End Sub

    Private Sub OpenEditLog(sender As Object, eventArgs As EventArgs)
        Using dialog As New EditLogViewerDialog(_editLog)
            dialog.ShowDialog(Me)
        End Using
    End Sub

    Private Shared Function EditLogPath() As String
        Dim directory = IO.Path.Combine(
            Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),
            "AutoGenerateDiameter",
            "logs"
        )
        IO.Directory.CreateDirectory(directory)
        Return IO.Path.Combine(directory, "edit-history.csv")
    End Function

    Private Function BuildCsv() As String
        Dim lines As New List(Of String) From {
            String.Join(",", {"Page", "TLabel", "TPosition", "Row", "DipLot", "Side", "Diameter", "TrayNumber", "Display", "Item", "PlateNo", "DateTime", "Capa", "DomeType", "Longtail83", "Longtail95", "CoatLotNo", "Operator"}.Select(AddressOf Csv))
        }
        For Each sheet In _report.Sheets
            For Each measurement In sheet.Measurements.OrderBy(Function(item) item.TrayPosition).ThenBy(Function(item) item.RowNumber)
                AddCsvSide(lines, sheet, measurement, "R", measurement.RPresent, measurement.RDash, measurement.RDiameter)
                AddCsvSide(lines, sheet, measurement, "L", measurement.LPresent, measurement.LDash, measurement.LDiameter)
            Next
        Next
        Return String.Join(Environment.NewLine, lines) & Environment.NewLine
    End Function

    Private Shared Sub AddCsvSide(lines As List(Of String), sheet As SheetData, measurement As Measurement, side As String, present As Boolean, dash As Boolean, diameter As Double)
        If Not present AndAlso Not dash Then Return
        Dim trayLabel = ((sheet.PageNumber - 1) * 22) + measurement.TrayPosition
        Dim diameterText = If(dash, "", Math.Round(diameter).ToString(CultureInfo.InvariantCulture))
        Dim display = If(dash, "-", diameterText)
        Dim values = {
            sheet.PageNumber.ToString(CultureInfo.InvariantCulture),
            $"T-{trayLabel}",
            measurement.TrayPosition.ToString(CultureInfo.InvariantCulture),
            measurement.RowNumber.ToString(CultureInfo.InvariantCulture),
            measurement.LotNumber,
            side,
            diameterText,
            measurement.TrayNumber,
            display,
            sheet.Item,
            sheet.PlateNo,
            sheet.DateTimeStamp,
            sheet.Capa,
            sheet.DomeType,
            sheet.Longtail83,
            sheet.Longtail95,
            sheet.CoatLotNo,
            sheet.OperatorName
        }
        lines.Add(String.Join(",", values.Select(AddressOf Csv)))
    End Sub

    Private Shared Function Csv(value As String) As String
        Dim text = If(value, "")
        Return $"""{text.Replace("""", """""")}"""
    End Function

    Private Sub ApplyReportDefaults(Optional repositionData As Boolean = True)
        If repositionData Then RepositionReportData(_startTrayPosition)
        For Each sheet In _report.Sheets
            sheet.Item = ""
            sheet.PlateNo = ""
            sheet.DateTimeStamp = ""
            sheet.DomeType = ""
            sheet.Capa = ""
            sheet.Longtail83 = ""
            sheet.Longtail95 = ""
            sheet.CoatLotNo = ""
            sheet.OperatorName = _operatorName
            sheet.StartTrayPosition = _startTrayPosition
        Next
    End Sub

    Private Sub RepositionReportData(newStartTrayPosition As Integer)
        If _report.Sheets.Count = 0 OrElse _report.MeasurementCount = 0 Then Return

        Dim oldStartTrayPosition = Math.Max(1, _report.Sheets(0).StartTrayPosition)
        Dim allMeasurements = _report.Sheets.
            SelectMany(Function(sheet) sheet.Measurements.Select(
                Function(measurement) New With {
                    .LogicalPosition = ((sheet.PageNumber - 1) * 22) + measurement.TrayPosition - oldStartTrayPosition + 1,
                    .Measurement = measurement
                }
            )).
            Where(Function(item) item.LogicalPosition >= 1).
            ToList()

        If allMeasurements.Count = 0 Then Return

        Dim maxDisplayPosition = allMeasurements.Max(Function(item) item.LogicalPosition + newStartTrayPosition - 1)
        Dim totalPages = Math.Max(1, CInt(Math.Ceiling(maxDisplayPosition / 22.0)))
        Dim template = _report.Sheets(0)
        Dim newSheets As New List(Of SheetData)

        For pageNumber = 1 To totalPages
            newSheets.Add(New SheetData With {
                .PageNumber = pageNumber,
                .TotalPages = totalPages,
                .Item = template.Item,
                .PlateNo = template.PlateNo,
                .DateTimeStamp = template.DateTimeStamp,
                .DomeType = template.DomeType,
                .Capa = template.Capa,
                .Longtail83 = template.Longtail83,
                .Longtail95 = template.Longtail95,
                .CoatLotNo = template.CoatLotNo,
                .OperatorName = template.OperatorName,
                .StartTrayPosition = newStartTrayPosition
            })
        Next

        For Each item In allMeasurements
            Dim displayPosition = item.LogicalPosition + newStartTrayPosition - 1
            Dim pageIndex = (displayPosition - 1) \ 22
            Dim trayPosition = ((displayPosition - 1) Mod 22) + 1
            newSheets(pageIndex).Measurements.Add(CloneMeasurement(item.Measurement, trayPosition))
        Next

        For Each sheet In newSheets
            sheet.Measurements = sheet.Measurements.
                OrderBy(Function(item) item.TrayPosition).
                ThenBy(Function(item) item.RowNumber).
                ToList()
        Next
        _report.Sheets = newSheets
        _pageIndex = Math.Clamp(_pageIndex, 0, _report.Sheets.Count - 1)
    End Sub

    Private Shared Function CloneMeasurement(source As Measurement, trayPosition As Integer) As Measurement
        Return New Measurement With {
            .TrayPosition = trayPosition,
            .RowNumber = source.RowNumber,
            .LotNumber = source.LotNumber,
            .RDiameter = source.RDiameter,
            .LDiameter = source.LDiameter,
            .TrayNumber = source.TrayNumber,
            .RPresent = source.RPresent,
            .LPresent = source.LPresent,
            .RDash = source.RDash,
            .LDash = source.LDash
        }
    End Function

    Private Function CanExportOrPrint() As Boolean
        Return True
    End Function

    Private NotInheritable Class CellSnapshot
        Public Property DisplayMode As String = "Blank"
        Public Property DisplayText As String = ""
        Public Property DiameterText As String = ""
        Public Property TrayNumber As String = ""
        Public Property LotNumber As String = ""

        Public Function HasSameValue(other As CellSnapshot) As Boolean
            Return DisplayMode = other.DisplayMode AndAlso
                DisplayText = other.DisplayText AndAlso
                DiameterText = other.DiameterText AndAlso
                TrayNumber = other.TrayNumber AndAlso
                LotNumber = other.LotNumber
        End Function
    End Class
End Class
