Option Strict On
Option Explicit On

Imports System.Drawing
Imports System.Drawing.Imaging
Imports System.Runtime.InteropServices

Public NotInheritable Class ImagePreprocessor
    Private Sub New()
    End Sub

    ' Preprocess a photo for OCR: grayscale → upscale → adaptive threshold.
    ' If sourcePath is an already-aligned temp file (prefix "AutoGenerateDiameter-aligned-"),
    ' the output keeps that prefix so LayoutFor() in ManualCompareService picks the right layout.
    Public Shared Function Preprocess(sourcePath As String) As String
        Dim isAligned = IO.Path.GetFileName(sourcePath).StartsWith(
            "AutoGenerateDiameter-aligned-", StringComparison.OrdinalIgnoreCase)
        Dim prefix = If(isAligned, "AutoGenerateDiameter-aligned-ocr-", "AutoGenerateDiameter-ocr-")
        Dim outputPath = IO.Path.Combine(IO.Path.GetTempPath(), $"{prefix}{Guid.NewGuid():N}.png")

        Using source As New Bitmap(sourcePath)
            Using gray = ToGrayscale(source)
                Using scaled = ScaleForOcr(gray)
                    Using thresholded = AdaptiveThreshold(scaled, scaled.Width \ 16, 0.85)
                        thresholded.Save(outputPath, ImageFormat.Png)
                    End Using
                End Using
            End Using
        End Using
        Return outputPath
    End Function

    ' Luminance-weighted grayscale via ColorMatrix.
    Private Shared Function ToGrayscale(source As Bitmap) As Bitmap
        Dim result As New Bitmap(source.Width, source.Height, PixelFormat.Format24bppRgb)
        Using g = Graphics.FromImage(result)
            Dim cm As New ColorMatrix(New Single()() {
                New Single() {0.299F, 0.299F, 0.299F, 0, 0},
                New Single() {0.587F, 0.587F, 0.587F, 0, 0},
                New Single() {0.114F, 0.114F, 0.114F, 0, 0},
                New Single() {0, 0, 0, 1, 0},
                New Single() {0, 0, 0, 0, 1}
            })
            Using attr As New ImageAttributes()
                attr.SetColorMatrix(cm)
                g.DrawImage(source,
                            New Rectangle(0, 0, source.Width, source.Height),
                            0, 0, source.Width, source.Height,
                            GraphicsUnit.Pixel, attr)
            End Using
        End Using
        Return result
    End Function

    ' Scale up to at least 2400px wide so Tesseract gets enough resolution.
    Private Shared Function ScaleForOcr(source As Bitmap) As Bitmap
        Const TargetWidth = 2400
        If source.Width >= TargetWidth Then Return New Bitmap(source)
        Dim scale = CDbl(TargetWidth) / source.Width
        Dim newWidth = TargetWidth
        Dim newHeight = CInt(source.Height * scale)
        Dim result As New Bitmap(newWidth, newHeight, PixelFormat.Format24bppRgb)
        Using g = Graphics.FromImage(result)
            g.InterpolationMode = Drawing2D.InterpolationMode.HighQualityBicubic
            g.DrawImage(source, 0, 0, newWidth, newHeight)
        End Using
        Return result
    End Function

    ' Bradley-Roth local threshold using an integral image.
    ' Each pixel becomes black if it falls below (T * local window mean), white otherwise.
    ' This handles reflections and uneven lighting by comparing locally rather than globally.
    Private Shared Function AdaptiveThreshold(source As Bitmap, windowSize As Integer, T As Double) As Bitmap
        Dim w = source.Width
        Dim h = source.Height
        Dim half = Math.Max(1, windowSize \ 2)

        Dim srcData = source.LockBits(
            New Rectangle(0, 0, w, h), ImageLockMode.ReadOnly, PixelFormat.Format24bppRgb)
        Dim srcStride = srcData.Stride
        Dim srcBytes(Math.Abs(srcStride) * h - 1) As Byte
        Marshal.Copy(srcData.Scan0, srcBytes, 0, srcBytes.Length)
        source.UnlockBits(srcData)

        ' Build integral image — Long avoids overflow on wide images.
        Dim integral(w * h - 1) As Long
        For y = 0 To h - 1
            Dim rowSum As Long = 0
            For x = 0 To w - 1
                ' Format24bppRgb: B=0, G=1, R=2; all equal after grayscale so use index 2.
                rowSum += srcBytes(y * srcStride + x * 3 + 2)
                integral(y * w + x) = rowSum + If(y > 0, integral((y - 1) * w + x), 0L)
            Next
        Next

        Dim result As New Bitmap(w, h, PixelFormat.Format24bppRgb)
        Dim dstData = result.LockBits(
            New Rectangle(0, 0, w, h), ImageLockMode.WriteOnly, PixelFormat.Format24bppRgb)
        Dim dstStride = dstData.Stride
        Dim dstBytes(Math.Abs(dstStride) * h - 1) As Byte

        For y = 0 To h - 1
            For x = 0 To w - 1
                Dim x1 = Math.Max(0, x - half)
                Dim y1 = Math.Max(0, y - half)
                Dim x2 = Math.Min(w - 1, x + half)
                Dim y2 = Math.Min(h - 1, y + half)
                Dim count = CLng(x2 - x1 + 1) * (y2 - y1 + 1)
                Dim sum = integral(y2 * w + x2) _
                        - If(x1 > 0, integral(y2 * w + x1 - 1), 0L) _
                        - If(y1 > 0, integral((y1 - 1) * w + x2), 0L) _
                        + If(x1 > 0 AndAlso y1 > 0, integral((y1 - 1) * w + x1 - 1), 0L)

                Dim pixel = CDbl(srcBytes(y * srcStride + x * 3 + 2))
                Dim output As Byte = If(pixel * count < sum * T, CByte(0), CByte(255))

                Dim dstOffset = y * dstStride + x * 3
                dstBytes(dstOffset) = output
                dstBytes(dstOffset + 1) = output
                dstBytes(dstOffset + 2) = output
            Next
        Next

        Marshal.Copy(dstBytes, 0, dstData.Scan0, dstBytes.Length)
        result.UnlockBits(dstData)
        Return result
    End Function
End Class
