Option Strict On
Option Explicit On

Imports System.Drawing
Imports System.Drawing.Imaging
Imports System.Runtime.InteropServices
Imports AutoGenerateDiameter.Core

Public NotInheritable Class ImagePreprocessor
    Private Sub New()
    End Sub

    ' Crop a single table cell from an aligned source image and preprocess it for isolated OCR.
    ' Steps: inset crop (drops the printed grid border) → grayscale → upscale → adaptive
    ' threshold → white padding (Tesseract needs a quiet margin around the glyphs).
    ' Returns a temp PNG path; ManualCompareService deletes it after OCR.
    Public Shared Function ExtractCell(sourcePath As String, region As CellRegion) As String
        Dim outputPath = IO.Path.Combine(IO.Path.GetTempPath(), $"AutoGenerateDiameter-ocr-cell-{Guid.NewGuid():N}.png")

        Using source As New Bitmap(sourcePath)
            ' Inset 12% on each side so the surrounding grid lines are excluded and only the
            ' handwritten number in the middle of the cell remains.
            Dim insetX = region.Width * 0.12
            Dim insetY = region.Height * 0.12
            Dim left = CInt(Math.Round((region.Left + insetX) * source.Width))
            Dim top = CInt(Math.Round((region.Top + insetY) * source.Height))
            Dim right = CInt(Math.Round((region.Left + region.Width - insetX) * source.Width))
            Dim bottom = CInt(Math.Round((region.Top + region.Height - insetY) * source.Height))

            left = Math.Max(0, Math.Min(left, source.Width - 1))
            top = Math.Max(0, Math.Min(top, source.Height - 1))
            right = Math.Max(left + 1, Math.Min(right, source.Width))
            bottom = Math.Max(top + 1, Math.Min(bottom, source.Height))

            Dim cropRect As New Rectangle(left, top, right - left, bottom - top)
            Using cell = CropRegion(source, cropRect)
                Using gray = ToGrayscale(cell)
                    Using scaled = ScaleCell(gray)
                        Using thresholded = AdaptiveThreshold(scaled, Math.Max(15, scaled.Width \ 4), 0.82)
                            Using padded = AddWhitePadding(thresholded, 28)
                                padded.Save(outputPath, ImageFormat.Png)
                            End Using
                        End Using
                    End Using
                End Using
            End Using
        End Using
        Return outputPath
    End Function

    Private Shared Function CropRegion(source As Bitmap, rect As Rectangle) As Bitmap
        Dim result As New Bitmap(rect.Width, rect.Height, PixelFormat.Format24bppRgb)
        Using g = Graphics.FromImage(result)
            g.DrawImage(source, New Rectangle(0, 0, rect.Width, rect.Height), rect, GraphicsUnit.Pixel)
        End Using
        Return result
    End Function

    ' Upscale a cropped cell so the smaller dimension is at least 220px (Tesseract reads
    ' small handwriting poorly below ~150px). Capped at 6x to avoid wasteful huge images.
    Private Shared Function ScaleCell(source As Bitmap) As Bitmap
        Const MinDimension = 220
        Dim smaller = Math.Min(source.Width, source.Height)
        If smaller <= 0 Then Return New Bitmap(source)
        Dim scale = Math.Min(6.0, Math.Max(1.0, MinDimension / CDbl(smaller)))
        If scale <= 1.0 Then Return New Bitmap(source)
        Dim newWidth = CInt(source.Width * scale)
        Dim newHeight = CInt(source.Height * scale)
        Dim result As New Bitmap(newWidth, newHeight, PixelFormat.Format24bppRgb)
        Using g = Graphics.FromImage(result)
            g.InterpolationMode = Drawing2D.InterpolationMode.HighQualityBicubic
            g.DrawImage(source, 0, 0, newWidth, newHeight)
        End Using
        Return result
    End Function

    Private Shared Function AddWhitePadding(source As Bitmap, padding As Integer) As Bitmap
        Dim result As New Bitmap(source.Width + padding * 2, source.Height + padding * 2, PixelFormat.Format24bppRgb)
        Using g = Graphics.FromImage(result)
            g.Clear(Color.White)
            g.DrawImageUnscaled(source, padding, padding)
        End Using
        Return result
    End Function

    ' Preprocess a photo for OCR: grayscale → upscale → adaptive threshold → grid-line removal.
    ' If sourcePath is an already-aligned temp file (prefix "AutoGenerateDiameter-aligned-"),
    ' the output keeps that prefix so LayoutFor() in ManualCompareService picks the right layout.
    Public Shared Function Preprocess(sourcePath As String) As String
        Dim isAligned = IO.Path.GetFileName(sourcePath).StartsWith(
            "AutoGenerateDiameter-aligned-", StringComparison.OrdinalIgnoreCase)
        Dim prefix = If(isAligned, "AutoGenerateDiameter-aligned-ocr-", "AutoGenerateDiameter-ocr-")
        Dim outputPath = IO.Path.Combine(IO.Path.GetTempPath(), $"{prefix}{Guid.NewGuid():N}.png")

        Using source As New Bitmap(sourcePath)
            Using gray = ToGrayscale(source)
                Using scaled = ScaleForOcr(gray)
                    ' Smaller window (width/24) catches fine strokes better than width/16.
                    ' T=0.82 is slightly more aggressive to capture faint ink.
                    Using thresholded = AdaptiveThreshold(scaled, scaled.Width \ 24, 0.82)
                        Using cleaned = RemoveGridLines(thresholded, 0.55, 0.55)
                            cleaned.Save(outputPath, ImageFormat.Png)
                        End Using
                    End Using
                End Using
            End Using
        End Using
        Return outputPath
    End Function

    ' Luminance-weighted grayscale via ColorMatrix.
    Private Shared Function ToGrayscale(source As Bitmap) As Bitmap
        Dim result As New Bitmap(source.Width, source.Height, PixelFormat.Format24bppRgb)
        Using g = Graphics.FromImage(result)
            Dim cm As New ColorMatrix(New Single()() {
                New Single() {0.299F, 0.299F, 0.299F, 0, 0},
                New Single() {0.587F, 0.587F, 0.587F, 0, 0},
                New Single() {0.114F, 0.114F, 0.114F, 0, 0},
                New Single() {0, 0, 0, 1, 0},
                New Single() {0, 0, 0, 0, 1}
            })
            Using attr As New ImageAttributes()
                attr.SetColorMatrix(cm)
                g.DrawImage(source,
                            New Rectangle(0, 0, source.Width, source.Height),
                            0, 0, source.Width, source.Height,
                            GraphicsUnit.Pixel, attr)
            End Using
        End Using
        Return result
    End Function

    ' Scale up to at least 2400px wide so Tesseract gets enough resolution.
    Private Shared Function ScaleForOcr(source As Bitmap) As Bitmap
        Const TargetWidth = 2400
        If source.Width >= TargetWidth Then Return New Bitmap(source)
        Dim scale = CDbl(TargetWidth) / source.Width
        Dim newWidth = TargetWidth
        Dim newHeight = CInt(source.Height * scale)
        Dim result As New Bitmap(newWidth, newHeight, PixelFormat.Format24bppRgb)
        Using g = Graphics.FromImage(result)
            g.InterpolationMode = Drawing2D.InterpolationMode.HighQualityBicubic
            g.DrawImage(source, 0, 0, newWidth, newHeight)
        End Using
        Return result
    End Function

    ' Bradley-Roth local threshold using an integral image.
    ' Each pixel becomes black if it falls below (T * local window mean), white otherwise.
    ' This handles reflections and uneven lighting by comparing locally rather than globally.
    Private Shared Function AdaptiveThreshold(source As Bitmap, windowSize As Integer, T As Double) As Bitmap
        Dim w = source.Width
        Dim h = source.Height
        Dim half = Math.Max(1, windowSize \ 2)

        Dim srcData = source.LockBits(
            New Rectangle(0, 0, w, h), ImageLockMode.ReadOnly, PixelFormat.Format24bppRgb)
        Dim srcStride = srcData.Stride
        Dim srcBytes(Math.Abs(srcStride) * h - 1) As Byte
        Marshal.Copy(srcData.Scan0, srcBytes, 0, srcBytes.Length)
        source.UnlockBits(srcData)

        ' Build integral image — Long avoids overflow on wide images.
        Dim integral(w * h - 1) As Long
        For y = 0 To h - 1
            Dim rowSum As Long = 0
            For x = 0 To w - 1
                ' Format24bppRgb: B=0, G=1, R=2; all equal after grayscale so use index 2.
                rowSum += srcBytes(y * srcStride + x * 3 + 2)
                integral(y * w + x) = rowSum + If(y > 0, integral((y - 1) * w + x), 0L)
            Next
        Next

        Dim result As New Bitmap(w, h, PixelFormat.Format24bppRgb)
        Dim dstData = result.LockBits(
            New Rectangle(0, 0, w, h), ImageLockMode.WriteOnly, PixelFormat.Format24bppRgb)
        Dim dstStride = dstData.Stride
        Dim dstBytes(Math.Abs(dstStride) * h - 1) As Byte

        For y = 0 To h - 1
            For x = 0 To w - 1
                Dim x1 = Math.Max(0, x - half)
                Dim y1 = Math.Max(0, y - half)
                Dim x2 = Math.Min(w - 1, x + half)
                Dim y2 = Math.Min(h - 1, y + half)
                Dim count = CLng(x2 - x1 + 1) * (y2 - y1 + 1)
                Dim sum = integral(y2 * w + x2) _
                        - If(x1 > 0, integral(y2 * w + x1 - 1), 0L) _
                        - If(y1 > 0, integral((y1 - 1) * w + x2), 0L) _
                        + If(x1 > 0 AndAlso y1 > 0, integral((y1 - 1) * w + x1 - 1), 0L)

                Dim pixel = CDbl(srcBytes(y * srcStride + x * 3 + 2))
                Dim output As Byte = If(pixel * count < sum * T, CByte(0), CByte(255))

                Dim dstOffset = y * dstStride + x * 3
                dstBytes(dstOffset) = output
                dstBytes(dstOffset + 1) = output
                dstBytes(dstOffset + 2) = output
            Next
        Next

        Marshal.Copy(dstBytes, 0, dstData.Scan0, dstBytes.Length)
        result.UnlockBits(dstData)
        Return result
    End Function

    ' Erase printed grid lines from a binary (black/white) image so Tesseract sees only ink.
    ' A row/column is treated as a grid line when its black-pixel density exceeds the threshold.
    ' horizontalThreshold / verticalThreshold: fraction of dimension that must be black (0–1).
    Private Shared Function RemoveGridLines(source As Bitmap, horizontalThreshold As Double, verticalThreshold As Double) As Bitmap
        Dim w = source.Width
        Dim h = source.Height

        Dim srcData = source.LockBits(
            New Rectangle(0, 0, w, h), ImageLockMode.ReadOnly, PixelFormat.Format24bppRgb)
        Dim stride = srcData.Stride
        Dim bytes(Math.Abs(stride) * h - 1) As Byte
        Marshal.Copy(srcData.Scan0, bytes, 0, bytes.Length)
        source.UnlockBits(srcData)

        ' Identify grid-line rows (horizontal lines spanning most of the width).
        Dim eraseRow(h - 1) As Boolean
        For y = 0 To h - 1
            Dim blackCount = 0
            For x = 0 To w - 1
                If bytes(y * stride + x * 3) = 0 Then blackCount += 1
            Next
            eraseRow(y) = blackCount / CDbl(w) >= horizontalThreshold
        Next

        ' Identify grid-line columns (vertical lines spanning most of the height).
        Dim eraseCol(w - 1) As Boolean
        For x = 0 To w - 1
            Dim blackCount = 0
            For y = 0 To h - 1
                If bytes(y * stride + x * 3) = 0 Then blackCount += 1
            Next
            eraseCol(x) = blackCount / CDbl(h) >= verticalThreshold
        Next

        ' Build output: erase (set white) any pixel on a detected grid line.
        Dim result As New Bitmap(w, h, PixelFormat.Format24bppRgb)
        Dim dstData = result.LockBits(
            New Rectangle(0, 0, w, h), ImageLockMode.WriteOnly, PixelFormat.Format24bppRgb)
        Dim dstStride = dstData.Stride
        Dim dstBytes(Math.Abs(dstStride) * h - 1) As Byte

        For y = 0 To h - 1
            For x = 0 To w - 1
                Dim srcVal = bytes(y * stride + x * 3)
                Dim outVal As Byte = If(eraseRow(y) OrElse eraseCol(x), CByte(255), srcVal)
                Dim offset = y * dstStride + x * 3
                dstBytes(offset) = outVal
                dstBytes(offset + 1) = outVal
                dstBytes(offset + 2) = outVal
            Next
        Next

        Marshal.Copy(dstBytes, 0, dstData.Scan0, dstBytes.Length)
        result.UnlockBits(dstData)
        Return result
    End Function
End Class
