Option Strict On
Option Explicit On

Imports AutoGenerateDiameter.Core

Public NotInheritable Class ReportPreviewControl
    Inherits Control

    Private Const PageWidth As Integer = 1600
    Private Const PageHeight As Integer = 1120
    Private Const HeaderBottom As Integer = 165
    Private Const FirstTrayTop As Integer = 175
    Private Const SecondTrayTop As Integer = 600
    Private Const TrayBlockHeight As Integer = 410
    Private Const TrayHeaderHeight As Integer = 24
    Private Shared ReadOnly DataColor As Color = Color.Blue
    Private _zoom As Single = 1.0F
    Private _scaleX As Single = 1.0F
    Private _scaleY As Single = 1.0F
    Private _sheet As SheetData
    Private _isPanning As Boolean
    Private _autoFit As Boolean = True
    Private _panStartScreen As Point
    Private _panStartScroll As Point

    Public Event CellDoubleClicked As EventHandler(Of ReportCellEventArgs)

    Public Sub New()
        DoubleBuffered = True
        BackColor = Color.White
        Cursor = Cursors.Hand
        UpdateSize()
    End Sub

    Public Property Sheet As SheetData
        Get
            Return _sheet
        End Get
        Set(value As SheetData)
            _sheet = value
            FitToParent()
            Invalidate()
        End Set
    End Property

    Protected Overrides Sub OnMouseWheel(e As MouseEventArgs)
        MyBase.OnMouseWheel(e)
        _autoFit = False
        _zoom = Math.Clamp(_zoom + If(e.Delta > 0, 0.1F, -0.1F), 0.45F, 1.5F)
        _scaleX = _zoom
        _scaleY = _zoom
        UpdateSize()
    End Sub

    Protected Overrides Sub OnParentChanged(e As EventArgs)
        MyBase.OnParentChanged(e)
        If Parent IsNot Nothing Then AddHandler Parent.Resize, AddressOf ParentResized
        FitToParent()
    End Sub

    Private Sub ParentResized(sender As Object, eventArgs As EventArgs)
        FitToParent()
    End Sub

    Protected Overrides Sub OnMouseDown(e As MouseEventArgs)
        MyBase.OnMouseDown(e)
        If e.Button <> MouseButtons.Left Then Return
        Dim viewport = TryCast(Parent, ScrollableControl)
        If viewport Is Nothing Then Return

        _isPanning = True
        _panStartScreen = PointToScreen(e.Location)
        _panStartScroll = New Point(
            -viewport.AutoScrollPosition.X,
            -viewport.AutoScrollPosition.Y
        )
        Capture = True
        Cursor = Cursors.SizeAll
    End Sub

    Protected Overrides Sub OnMouseMove(e As MouseEventArgs)
        MyBase.OnMouseMove(e)
        If Not _isPanning Then Return
        Dim viewport = TryCast(Parent, ScrollableControl)
        If viewport Is Nothing Then Return

        Dim currentScreen = PointToScreen(e.Location)
        Dim deltaX = currentScreen.X - _panStartScreen.X
        Dim deltaY = currentScreen.Y - _panStartScreen.Y
        viewport.AutoScrollPosition = New Point(
            Math.Max(0, _panStartScroll.X - deltaX),
            Math.Max(0, _panStartScroll.Y - deltaY)
        )
    End Sub

    Protected Overrides Sub OnMouseUp(e As MouseEventArgs)
        MyBase.OnMouseUp(e)
        If e.Button <> MouseButtons.Left Then Return
        _isPanning = False
        Capture = False
        Cursor = Cursors.Hand
    End Sub

    Protected Overrides Sub OnMouseCaptureChanged(e As EventArgs)
        MyBase.OnMouseCaptureChanged(e)
        If Capture Then Return
        _isPanning = False
        Cursor = Cursors.Hand
    End Sub

    Protected Overrides Sub OnMouseDoubleClick(e As MouseEventArgs)
        MyBase.OnMouseDoubleClick(e)
        If e.Button <> MouseButtons.Left Then Return
        Dim hit = HitTestCell(e.Location)
        If hit Is Nothing Then Return
        RaiseEvent CellDoubleClicked(Me, New ReportCellEventArgs(hit))
    End Sub

    Protected Overrides Sub OnPaint(e As PaintEventArgs)
        MyBase.OnPaint(e)
        If _sheet Is Nothing Then Return
        e.Graphics.ScaleTransform(_scaleX, _scaleY)
        RenderSheet(e.Graphics, _sheet)
    End Sub

    Public Shared Sub RenderSheetToBounds(graphics As Graphics, sheet As SheetData, bounds As RectangleF)
        If sheet Is Nothing Then Return
        graphics.FillRectangle(Brushes.White, bounds)
        Dim state As Drawing2D.GraphicsState = graphics.Save()
        Try
            Dim scale = Math.Min(bounds.Width / PageWidth, bounds.Height / PageHeight)
            Dim renderWidth = PageWidth * scale
            Dim renderHeight = PageHeight * scale
            graphics.TranslateTransform(
                bounds.Left + (bounds.Width - renderWidth) / 2.0F,
                bounds.Top + (bounds.Height - renderHeight) / 2.0F
            )
            graphics.ScaleTransform(scale, scale)
            RenderSheet(graphics, sheet)
        Finally
            graphics.Restore(state)
        End Try
    End Sub

    Private Shared Sub RenderSheet(graphics As Graphics, sheet As SheetData)
        graphics.Clear(Color.White)
        DrawHeader(graphics, sheet)
        DrawTrayBlock(graphics, sheet, FirstTrayTop, 1)
        DrawTrayBlock(graphics, sheet, SecondTrayTop, 12)
        DrawFooter(graphics, sheet)
    End Sub

    Private Sub UpdateSize()
        Size = New Size(CInt(PageWidth * _scaleX), CInt(PageHeight * _scaleY))
        Invalidate()
    End Sub

    Private Sub FitToParent()
        If Not _autoFit Then Return
        Dim viewport = TryCast(Parent, Control)
        If viewport Is Nothing OrElse viewport.ClientSize.Width <= 0 OrElse viewport.ClientSize.Height <= 0 Then Return
        Dim availableWidth = Math.Max(1, viewport.ClientSize.Width)
        Dim availableHeight = Math.Max(1, viewport.ClientSize.Height)
        _scaleX = Math.Clamp(availableWidth / CSng(PageWidth), 0.45F, 1.8F)
        _scaleY = Math.Clamp(availableHeight / CSng(PageHeight), 0.45F, 1.8F)
        _zoom = Math.Min(_scaleX, _scaleY)
        UpdateSize()
    End Sub

    Private Function HitTestCell(location As Point) As ReportCellHit
        If _sheet Is Nothing OrElse _scaleX <= 0 OrElse _scaleY <= 0 Then Return Nothing

        Dim logicalX = location.X / _scaleX
        Dim logicalY = location.Y / _scaleY
        Dim firstPosition = 1
        Dim top = FirstTrayTop

        If logicalY >= SecondTrayTop AndAlso logicalY <= SecondTrayTop + TrayBlockHeight Then
            firstPosition = 12
            top = SecondTrayTop
        ElseIf logicalY < FirstTrayTop OrElse logicalY > FirstTrayTop + TrayBlockHeight Then
            Return Nothing
        End If

        Dim trayWidth = PageWidth / 11.0F
        If logicalX < 0 OrElse logicalX > PageWidth Then Return Nothing
        Dim column = Math.Min(10, CInt(Math.Floor(logicalX / trayWidth)))
        Dim trayPosition = firstPosition + column
        If trayPosition < 1 OrElse trayPosition > 22 Then Return Nothing

        Dim dataTop = top + TrayHeaderHeight * 2
        Dim rowHeight = (TrayBlockHeight - TrayHeaderHeight * 2) / 6.0F
        If logicalY < dataTop OrElse logicalY > dataTop + rowHeight * 6 Then Return Nothing

        Dim rowNumber = Math.Min(6, CInt(Math.Floor((logicalY - dataTop) / rowHeight)) + 1)
        Dim left = column * trayWidth
        Dim side = If(logicalX < left + trayWidth / 2.0F, "R", "L")
        Dim trayLabel = ((_sheet.PageNumber - 1) * 22) + trayPosition

        Return New ReportCellHit With {
            .TrayPosition = trayPosition,
            .TrayLabel = trayLabel,
            .RowNumber = rowNumber,
            .Side = side
        }
    End Function

    Private Shared Sub DrawHeader(graphics As Graphics, sheet As SheetData)
        DrawLine(graphics, 0, 22, PageWidth, 22)
        DrawLine(graphics, 1165, 0, 1165, 22)
        DrawLine(graphics, 1385, 0, 1385, 22)
        DrawText(graphics, "PAGE NO", 1175, 11, 9, True, Color.Black, ContentAlignment.MiddleLeft)
        DrawText(graphics, $"{sheet.PageNumber}/{sheet.TotalPages}", 1490, 11, 16, True, DataColor)
        DrawField(graphics, "ITEM", sheet.Item, 5, 72, 100, 26)
        DrawField(graphics, "PLATE No.", sheet.PlateNo, 455, 72, 655, 26)
        DrawText(graphics, "Longtail", 950, 72, 26, True, Color.Black, ContentAlignment.MiddleLeft)
        DrawText(graphics, "Delay", 1175, 72, 26, True, Color.Black, ContentAlignment.MiddleLeft)
        DrawField(graphics, "DATETIME", sheet.DateTimeStamp, 5, 127, 170, 22)
        DrawField(graphics, "CAPA.", sheet.Capa, 380, 127, 485, 22)
        DrawText(graphics, "P'cs", 660, 127, 22, True, Color.Black, ContentAlignment.MiddleLeft)
        DrawField(graphics, "DOME Type", sheet.DomeType, 790, 127, 940, 18)
        DrawText(graphics, sheet.Longtail83, 1040, 127, 22, True, DataColor)
        DrawText(graphics, sheet.Longtail95, 1120, 127, 22, True, DataColor)
        DrawField(graphics, "Coat Lot No.", sheet.CoatLotNo, 1175, 127, 1325, 18)
        DrawLine(graphics, 0, HeaderBottom, PageWidth, HeaderBottom)
    End Sub

    Private Function IsBlankSheet() As Boolean
        Return _sheet.Measurements.Count = 0 AndAlso
            String.IsNullOrWhiteSpace(_sheet.Item) AndAlso
            String.IsNullOrWhiteSpace(_sheet.PlateNo) AndAlso
            String.IsNullOrWhiteSpace(_sheet.DateTimeStamp) AndAlso
            String.IsNullOrWhiteSpace(_sheet.DomeType) AndAlso
            String.IsNullOrWhiteSpace(_sheet.Capa) AndAlso
            String.IsNullOrWhiteSpace(_sheet.Longtail83) AndAlso
            String.IsNullOrWhiteSpace(_sheet.Longtail95) AndAlso
            String.IsNullOrWhiteSpace(_sheet.CoatLotNo) AndAlso
            String.IsNullOrWhiteSpace(_sheet.OperatorName)
    End Function

    Private Shared Sub DrawField(graphics As Graphics, label As String, value As String, labelX As Single, y As Single, valueX As Single, labelSize As Single)
        DrawText(graphics, label, labelX, y, labelSize, True, Color.Black, ContentAlignment.MiddleLeft)
        DrawText(graphics, value, valueX + 8, y + 3, 16, True, DataColor, ContentAlignment.MiddleLeft)
    End Sub

    Private Shared Sub DrawTrayBlock(graphics As Graphics, sheet As SheetData, top As Integer, firstPosition As Integer)
        Dim bottom = top + TrayBlockHeight
        Dim trayWidth = PageWidth / 11.0F
        Dim rowHeight = (TrayBlockHeight - TrayHeaderHeight * 2) / 6.0F
        DrawLine(graphics, 0, top, PageWidth, top)
        DrawLine(graphics, 0, bottom, PageWidth, bottom)

        For column = 0 To 10
            Dim trayPosition = firstPosition + column
            Dim left = column * trayWidth
            Dim middle = left + trayWidth / 2
            Dim right = left + trayWidth
            Dim measurements = sheet.Measurements.Where(Function(item) item.TrayPosition = trayPosition).ToList()
            Dim lot = If(measurements.Count = 0, "", measurements(0).LotNumber)
            DrawLine(graphics, left, top, left, bottom)
            DrawLine(graphics, middle, top + TrayHeaderHeight, middle, bottom)
            DrawLine(graphics, left, top + TrayHeaderHeight, right, top + TrayHeaderHeight)
            DrawLine(graphics, left, top + TrayHeaderHeight * 2, right, top + TrayHeaderHeight * 2)
            Dim trayLabel = ((sheet.PageNumber - 1) * 22) + trayPosition
            DrawText(graphics, $"T-{trayLabel}", left + 8, top + 12, 12, True, Color.Black, ContentAlignment.MiddleLeft)
            DrawText(graphics, lot, middle, top + 12, 14, True, DataColor)
            DrawText(graphics, "R", left + trayWidth * 0.25F, top + 36, 12, True, Color.Black)
            DrawText(graphics, "L", left + trayWidth * 0.75F, top + 36, 12, True, Color.Black)

            For row = 1 To 6
                Dim rowTop = top + TrayHeaderHeight * 2 + (row - 1) * rowHeight
                DrawLine(graphics, left, rowTop + rowHeight, right, rowTop + rowHeight)
                DrawText(graphics, row.ToString(), left + 5, rowTop + rowHeight / 2, 12, True, Color.Black, ContentAlignment.MiddleLeft)
            Next

            For Each measurement In measurements
                Dim rowTop = top + TrayHeaderHeight * 2 + (measurement.RowNumber - 1) * rowHeight
                If measurement.RDash Then
                    DrawDash(graphics, left + trayWidth * 0.25F, rowTop, rowHeight)
                ElseIf measurement.RPresent Then
                    DrawCell(graphics, left + trayWidth * 0.25F, rowTop, rowHeight, measurement.RDiameter, measurement.TrayNumber)
                End If
                If measurement.LDash Then
                    DrawDash(graphics, left + trayWidth * 0.75F, rowTop, rowHeight)
                ElseIf measurement.LPresent Then
                    DrawCell(graphics, left + trayWidth * 0.75F, rowTop, rowHeight, measurement.LDiameter, measurement.TrayNumber)
                End If
            Next
        Next
        DrawLine(graphics, PageWidth - 1, top, PageWidth - 1, bottom)
    End Sub

    Private Shared Sub DrawCell(graphics As Graphics, x As Single, rowTop As Single, rowHeight As Single, diameter As Double, trayNumber As String)
        DrawText(graphics, Math.Round(diameter).ToString(), x, rowTop + rowHeight * 0.25F, 14, True, DataColor)
        DrawText(graphics, trayNumber, x, rowTop + rowHeight * 0.75F, 12, True, DataColor)
    End Sub

    Private Shared Sub DrawDash(graphics As Graphics, x As Single, rowTop As Single, rowHeight As Single)
        DrawText(graphics, "-", x, rowTop + rowHeight * 0.5F, 16, True, DataColor)
    End Sub

    Private Shared Sub DrawFooter(graphics As Graphics, sheet As SheetData)
        DrawLine(graphics, 0, 1025, PageWidth, 1025)
        DrawText(graphics, "LENS TEST", 5, 1053, 18, True, Color.Black, ContentAlignment.MiddleLeft)
        DrawText(graphics, $"Operator  {sheet.OperatorName}", 1320, 1053, 22, True, DataColor, ContentAlignment.MiddleLeft)
    End Sub

    Private Shared Sub DrawLine(graphics As Graphics, x1 As Single, y1 As Single, x2 As Single, y2 As Single)
        graphics.DrawLine(Pens.Black, x1, y1, x2, y2)
    End Sub

    Private Shared Sub DrawText(
        graphics As Graphics,
        text As String,
        x As Single,
        y As Single,
        size As Single,
        bold As Boolean,
        color As Color,
        Optional alignment As ContentAlignment = ContentAlignment.MiddleCenter
    )
        Using font As New Font("Arial", size, If(bold, FontStyle.Bold, FontStyle.Regular), GraphicsUnit.Pixel)
            Using brush As New SolidBrush(color)
                Dim format As New StringFormat With {.LineAlignment = StringAlignment.Center}
                Select Case alignment
                    Case ContentAlignment.MiddleLeft
                        format.Alignment = StringAlignment.Near
                    Case ContentAlignment.MiddleRight
                        format.Alignment = StringAlignment.Far
                    Case Else
                        format.Alignment = StringAlignment.Center
                End Select
                graphics.DrawString(text, font, brush, New PointF(x, y), format)
            End Using
        End Using
    End Sub
End Class

Public NotInheritable Class ReportCellHit
    Public Property TrayPosition As Integer
    Public Property TrayLabel As Integer
    Public Property RowNumber As Integer
    Public Property Side As String = ""
End Class

Public NotInheritable Class ReportCellEventArgs
    Inherits EventArgs

    Public ReadOnly Property Hit As ReportCellHit

    Public Sub New(hit As ReportCellHit)
        Me.Hit = hit
    End Sub
End Class
