param(
    [string]$Version = "1.0.0",
    [string]$InnoSetupPath = "D:\Inno Setup 6\ISCC.exe"
)

$ErrorActionPreference = "Stop"
$root = $PSScriptRoot
$project = Join-Path $root "AutoGenerateDiameter.WinForms\AutoGenerateDiameter.WinForms.vbproj"
$publish = Join-Path $root "publish\win-x64"
$installer = Join-Path $root "installer\AutoGenerateDiameter.iss"

if (-not (Test-Path -LiteralPath $InnoSetupPath)) {
    throw "ISCC.exe not found: $InnoSetupPath"
}

dotnet publish $project `
    -c Release `
    -r win-x64 `
    --self-contained true `
    -p:PublishSingleFile=false `
    -o $publish

if ($LASTEXITCODE -ne 0) {
    throw "dotnet publish failed."
}

& $InnoSetupPath "/DMyAppVersion=$Version" $installer
if ($LASTEXITCODE -ne 0) {
    throw "Inno Setup compile failed."
}

Write-Host "Installer created:"
Write-Host (Join-Path $root "installer\output\AutoGenerateDiameterSetup-x64.exe")
